Feature/orion port
NOAA-EMC/regional_workflow pull request #309
Opened 2020-10-09 23:43 UTC by gsketefian

- Use this template to give a detailed message describing the change you want to make to the code.

- You may delete any sections labeled "optional".

- If you are unclear on what should be written here, see https://github.com/wrf-model/WRF/wiki/Making-a-good-pull-request-message for some guidance. 

- The title of this pull request should be a brief summary (ideally less than 100 characters) of the changes included in this PR.

- Use the "Preview" tab to see what your PR will look like when you hit "Create pull request"

# --- Delete this line and those above before hitting "Create pull request" ---

## DESCRIPTION OF CHANGES: 
One or more paragraphs describing the problem, solution, and required changes.

## TESTS CONDUCTED: 
Explicitly state what tests were run on these changes, or if any are still pending (for README or other text-only changes, just put "None required". Make note of the compilers used, the platform/machine, and other relevant details as necessary. For more complicated changes, or those resulting in scientific changes, please be explicit!

## ISSUE (optional): 
If this PR is resolving or referencing one or more issues, in this repository or elewhere, list them here. For example, "Fixes issue mentioned in #123" or "Related to bug in https://github.com/NOAA-EMC/other_repository/pull/63"

## CONTRIBUTORS (optional): 
If others have contributed to this work aside from the PR author, list them here

2020-10-14 19:45 UTC, gsketefian commented
@mkavulich @JulieSchramm Can one of you test a case on cheyenne?
@JeffBeck-NOAA Are you planning on testing on hera and/or jet?  I can test on hera relatively easily since I can run X2Go there (I can't on jet).

2020-10-14 19:56 UTC, JeffBeck-NOAA commented
> @mkavulich @JulieSchramm Can one of you test a case on cheyenne?
> @JeffBeck-NOAA Are you planning on testing on hera and/or jet? I can test on hera relatively easily since I can run X2Go there (I can't on jet).

@gsketefian, if you're able to test things quickly on Hera, please feel free.  If you'd like me to test on Jet, I'm happy to do that.

2020-10-14 20:14 UTC, gsketefian commented
@JeffBeck-NOAA Ok, please go ahead and test on Jet.  I will test on Hera.

2020-10-15 20:56 UTC, christinaholtNOAA commented
Should I be getting a regional_workflow module set up on Orion for this?

2020-10-15 21:38 UTC, gsketefian commented
> Should I be getting a regional_workflow module set up on Orion for this?

I was going to look into that with the sysadmins soon, but if you don't mind, that would be great.  This is what I do now before generating an experiment:

> module load python/3.7
> export PYTHONPATH="/home/gketefia/miniconda3/pkgs/jinja2-2.11.2-py_0/site-packages:$PYTHONPATH"

Their python/3.7 gets us most of the way there except for jinja2, which is not recent enough (that's why I add the path to my installation).  Thanks!

2020-10-15 21:52 UTC, christinaholtNOAA commented
I think it's important to make sure that we have the ability to run the stand-alone utilities in jobs, too. So having an installation all in one place, and managed the same way would be more ideal.

2020-10-15 23:06 UTC, gsketefian commented
> I think it's important to make sure that we have the ability to run the stand-alone utilities in jobs, too. So having an installation all in one place, and managed the same way would be more ideal.

Ok, sounds good!  Please post an announcement here when it's ready and we can try it.

2020-10-16 21:27 UTC, JeffBeck-NOAA approved these changes

2020-10-16 23:43 UTC, gsketefian commented
I'm going to merge this since it does pretty well on 3 machines.  We can test on Jet when its filesystem issues are resolved.

2020-10-16 23:44 UTC, gsketefian commented
Oh never mind, I don't have administrator access to the repo any longer due to the repo delete/restore.  Will have to wait until rights have been restored.

2020-10-18 04:53 UTC, JeffBeck-NOAA commented
@gsketefian, I was able to test this PR on Jet this evening.  The HPSS tasks fail due to the following configuration:

<!ENTITY RSRV_HPSS    "<account>&ACCOUNT;</account><queue>&QUEUE_HPSS;</queue><partition>service</partition>">
 
The error message is: sbatch: error: Batch job submission failed: Invalid qos specification

Changing the RSRV_HPSS line to the following fixes the problem:

<!ENTITY RSRV_HPSS    "<account>&ACCOUNT;</account><partition>&QUEUE_HPSS;</partition>">

I'm not sure if this requires a separate "if Jet, then formulate the RSRV_HPSS entity like this" statement or not.

2020-10-19 15:32 UTC, gsketefian commented
@JeffBeck-NOAA I think this is the same problem I encountered on hera and committed a bug fix for (for both hera and jet) via commit #bbe8d58 (see above).  What hash are you currently on?  If you don't have that commit, can you try pulling the HEAD of this branch and rerunning?  Thanks.

2020-10-19 15:59 UTC, mkavulich commented
@gsketefian When I try to generate the workflow on Orion using the python environment you specified, I get an error 

`python module f90nml not available`

2020-10-19 16:24 UTC, JeffBeck-NOAA commented
@gsketefian, Can you check the HEAD of your feature branch again?  I still have the following in the XML:

`<!ENTITY RSRV_HPSS    "<account>&ACCOUNT;</account><queue>&QUEUE_HPSS;</queue><partition>service</partition>">`

with `<!ENTITY QUEUE_HPSS "service">`

2020-10-19 16:45 UTC, mkavulich requested changes

2020-10-19 16:45 UTC, mkavulich commented on tests/run_experiments.sh
> -#!/bin/bash -l
I agree that this is a good change ([info on "-l" bash shebang option](https://stackoverflow.com/questions/20499596/bash-shebang-option-l), it seems dangerous in that it allows the user's environment to make potentially unexpected changes), but are we sure this will not break things on other platforms?

There are other files that also include this option (namely, launch_FV3LAM_wflow.sh) that should probably be removed...maybe it's better to handle that in a different PR that is more widely tested?

2020-10-19 16:45 UTC, mkavulich commented on ush/generate_FV3LAM_wflow.sh
> -  'partition_run_fcst': sjet,vjet,kjet,xjet
Definitely needs a Jet test before merging due to this change; I can take care of that now as I believe the file system issues have been resolved.

2020-10-19 16:45 UTC, mkavulich commented on modulefiles/tasks/orion/make_grid.local
> +#module use -a /contrib/miniconda3/modulefiles
I assume these will be updated to load the correct environment before merging?

2020-10-19 16:56 UTC, gsketefian commented on ush/generate_FV3LAM_wflow.sh
> -  'partition_run_fcst': sjet,vjet,kjet,xjet
Jeff tested on Jet already and found a bug which I think is the same one I found on hera and fixed.  I asked him to retry after pulling the latest (I don't think he had the latest); see above.  But it would be good if you try as well.

2020-10-19 16:59 UTC, JeffBeck-NOAA commented
@gsketefian, not sure if you saw my earlier message above, but I pulled the HEAD and still have the same problem.

2020-10-19 16:59 UTC, gsketefian commented on modulefiles/tasks/orion/make_grid.local
> +#module use -a /contrib/miniconda3/modulefiles
Yes.  @christinaholtNOAA is working on creating the proper miniconda environment on Orion.  Once that's done, we'll uncomment/edit these module files.  For now, before generating an experiment/workflow, the user has to first run the two lines I included in the Caveats section of the PR message above (load proper version of python and point to a recent-enough version of jinja2 that is in one of my directories).

2020-10-19 17:04 UTC, gsketefian commented on tests/run_experiments.sh
> -#!/bin/bash -l
I'd like to eventually remove the "-l"s everywhere they appear in the scripts so that they are all independent of what the user has in their .bash_profile (and maybe .bashrc and/or .login).  I had to remove this particular one because otherwise I was encountering an error (can't remember what it was or on which platform; I think Orion).  We're testing on Hera, Orion, Cheyenne, and Jet, so that's pretty inclusive.

2020-10-19 17:11 UTC, gsketefian commented
> @gsketefian When I try to generate the workflow on Orion using the python environment you specified, I get an error
> 
> `python module f90nml not available`

Ok, there might be other paths that need to be added to the PYTHONPATH variable that are in my PATH (e.g. one for f90nml) that I forgot about.  Let me try a couple of things.

2020-10-19 17:34 UTC, christinaholtNOAA reviewed
It could be helpful to share the behavior of the Jet issue here so that more folks could help debug.

I heard back from Orion Help this morning with a question about creating a contrib module, but haven't had any forward movement so far.

2020-10-19 17:34 UTC, christinaholtNOAA commented on ush/generate_FV3LAM_wflow.sh
> +
There really shouldn't be any XML in this file at all since there is an XML template that is capable of handling this logic in place.

2020-10-19 22:58 UTC, gsketefian commented
> > @gsketefian When I try to generate the workflow on Orion using the python environment you specified, I get an error
> > `python module f90nml not available`
> 
> Ok, there might be other paths that need to be added to the PYTHONPATH variable that are in my PATH (e.g. one for f90nml) that I forgot about. Let me try a couple of things.

@mkavulich Can you try this new setting of PYTHONPATH (which I've also modified in the PR statement):
`> export PYTHONPATH="/home/gketefia/.local/lib/python3.7/site-packages:/home/gketefia/miniconda3/pkgs/jinja2-2.11.2-py_0/site-packages:$PYTHONPATH"
`
This is of course temporary until Christina gets the regional_workflow environment set up.

2020-10-20 16:40 UTC, gsketefian commented on ush/generate_FV3LAM_wflow.sh
> +
I moved that partition logic into the XML template.

2020-10-20 19:14 UTC, gsketefian commented
@RatkoVasic-NOAA @ywangwof If/when you get a chance to test this on WCOSS_CRAY, WCOSS_DELL_P3, ODIN, and/or STAMPEDE, please let me know.

2020-10-20 19:33 UTC, gsketefian commented
@RatkoVasic-NOAA I don't know exactly what Ben does to run it on WCOSS_CRAY and WCOSS_DELL_P3, so I can't tell you exactly what to do.  The generic instructions on how to run it are [here](https://github.com/ufs-community/ufs-srweather-app/wiki/Getting-Started), if that helps.  Those work on hera, cheyenne, and orion, at least.  We can wait for Ben to run it if he's going to be back soon.  We have to wait at least until tomorrow anyway to debug this on jet (jet is down today).  Doing this test isn't absolutely necessary before merging; we can take care of any bugs after merging it if EMC doesn't mind.

2020-10-20 19:47 UTC, gsketefian commented
> @gsketefian, Can you check the HEAD of your feature branch again? I still have the following in the XML:
> 
> `<!ENTITY RSRV_HPSS "<account>&ACCOUNT;</account><queue>&QUEUE_HPSS;</queue><partition>service</partition>">`
> 
> with `<!ENTITY QUEUE_HPSS "service">`

@JeffBeck-NOAA After looking at this more carefully, it looks like you may not have the HEAD of the repo because in the HEAD, ENTITY QUEUE_HPSS should be getting set to "batch", not "service".  That's the bug I fixed.  You can check setup.sh around line 402 to see if that's really the case.  If QUEUE_HPSS is getting set to "service" in setup.sh, then it means you don't have the latest version.

2020-10-20 20:20 UTC, christinaholtNOAA commented
Orion Help has issued me some contrib module space and I will work toward installing miniconda and a regional_workflow environment there this afternoon and tomorrow. I'll get back to you when it's ready.

2020-10-20 20:35 UTC, christinaholtNOAA commented
That was a quick path to an update....looks like system maintenance might push this activity to tomorrow.

2020-10-20 20:47 UTC, JeffBeck-NOAA commented
> s

Thanks @gsketefian, I'll take a look.

2020-10-20 20:47 UTC, JeffBeck-NOAA commented
> > @gsketefian, Can you check the HEAD of your feature branch again? I still have the following in the XML:
> > `<!ENTITY RSRV_HPSS "<account>&ACCOUNT;</account><queue>&QUEUE_HPSS;</queue><partition>service</partition>">`
> > with `<!ENTITY QUEUE_HPSS "service">`
> 
> @JeffBeck-NOAA After looking at this more carefully, it looks like you may not have the HEAD of the repo because in the HEAD, ENTITY QUEUE_HPSS should be getting set to "batch", not "service". That's the bug I fixed. You can check setup.sh around line 402 to see if that's really the case. If QUEUE_HPSS is getting set to "service" in setup.sh, then it means you don't have the latest version.

Thanks @gsketefian, I'll take a look.

2020-10-21 14:31 UTC, christinaholtNOAA commented
I have a contrib module installed on Orion now. I have tested in a default bash environment (not entirely sure if Orion supports other defaults).

Please test it out and let me know if you are seeing any weird behavior. This is a newer version of miniconda as well as the packages, so we might need some modifications to the module or the environment to get the desired result.

To use it:

```
module use -a /apps/contrib/miniconda3-noaa-gsl/modulefiles
module load miniconda3
conda activate regional_workflow
```

2020-10-21 17:47 UTC, ywangwof commented
@gsketefian I tested your branch on Odin and Stampede with the community workflow for 13 km and 25 km. I will suggest the following changes

1. _ush/config.community.sh_. It seems that both **PARTITION** and **QUEUE** variables are required. I do not know why, but just added the following for the workflow generator to work.

```
PARTITION_DEFAULT="batch"
PARTITION_HPSS="service"
PARTITION_FCST="batch"
```

2. _ush/wrappers/run_post.sh_. The file names contain 3 digits now. So I change this line

> export fhr=\`printf "%03i" ${I}\`

If it is more convenient, you can check out my branch "**feature/orion_port/odin_test**" here, https://github.com/ywangwof/regional_workflow, which is based on your branch "**feature/orion_port**"

Thanks.

2020-10-21 18:52 UTC, gsketefian commented
@christinaholtNOAA Thanks for doing that.  I will put those lines in the appropriate module files for orion and test.

2020-10-21 19:41 UTC, gsketefian commented
@ywangwof That was also a problem on hera because it was overriding the default values that get set in setup.sh (in the case-statement starting around line 362).  I solved it on hera by not including any PARTITION_... and QUEUE_... settings in config.community.sh.  That way, the workflow will use whatever is set in that case statement.  I just committed this change.

I do not know what the slurm partitions and QOS's are called on Stampede and Odin.  In my commit, I also included new lines for PARTITION_... in that case statement in the Stampede and Odin stanza, but I left the default values blank.  Do you mind filling out those default values (and setting the QUEUE_... values to the proper QOS's as well if they are wrong) and then testing again with the new config.community.sh?  That will verify whether those default values are correct.

2020-10-21 20:37 UTC, JeffBeck-NOAA commented
@gsketefian I can confirm that the updated PR now runs to completion on Jet.

2020-10-21 20:51 UTC, gsketefian commented
@ywangwof Forgot about that change to the wrapper script.  Will make the change and push.

2020-10-21 21:33 UTC, ywangwof commented
@gsketefian Thanks. On Odin and Stampede, they do not distinguish PARTITION and QUEUE. In setup.sh, I just set all `PARTITION_*=${PARTITION_*:-"normal"}` on Stampede
`PARTITION_*=${PARTITION_*:-"workq"} `on Odin

The scripts was tested again and the community workflow runs to completion on both Odin and Stampede.

2020-10-21 21:44 UTC, gsketefian commented
@ywangwof That's great, thanks for doing that!  I'll make those changes in my branch and push.

2020-10-21 22:31 UTC, gsketefian commented
@ywangwof I just realized I'm not sure how to set the QUEUE_... variables.  Like this?
QUEUE_*=${QUEUE_*:-"normal"} on Stampede
QUEUE_*=${QUEUE_*:-"workq"} on Odin

2020-10-21 22:55 UTC, ywangwof commented
@gsketefian That will work.

2020-10-23 00:45 UTC, mkavulich commented on tests/run_experiments.sh
> -#!/bin/bash -l
Okay, I will open an issue to get to the rest of those "bash -l" instances removed.

2020-10-23 17:16 UTC, JeffBeck-NOAA commented
With the mods for both Odin/Stampede, and the successful test on Jet, are we ready to merge this PR.  Are there any remaining issues with the Python contrib module on Orion?

2020-10-23 18:00 UTC, gsketefian commented
@JeffBeck-NOAA Yes, there are still issues on Orion after I put Christina's lines in the module files.  I'll back on what's happening in a bit so Christina can take a look.

2020-10-23 21:39 UTC, gsketefian commented
@JeffBeck-NOAA I take that back.  Everything seems to be working fine on Orion with the changes to the module files.

@mkavulich What was the change you requested?  Does it have to do with the "-l" option to bash?

It would be great if someone other than me could also run a case with the latest version of this on orion to make sure it works for someone else's environment as well.

2020-10-24 23:08 UTC, JeffBeck-NOAA approved these changes
After running an end-to-end test on Orion successfully, I'm now approving this PR.  However, Gerard and I are running into the following conda error:

/apps/contrib/miniconda3-noaa-gsl/3.8/etc/profile.d/conda.sh: line 57: PS1: unbound variable

@christinaholtNOAA, would you be able to take a look at this?  Thank you!

2020-10-26 07:38 UTC, gsketefian commented
@mkavulich Since @JeffBeck-NOAA successfully tested this on Jet, I'm going to assume your requested changes have been satisfied.

2020-10-26 07:41 UTC, gsketefian commented
@JeffBeck-NOAA The error we were both experiencing (having to do with PS1 being an undefined variable) is again not happening for me.  It's not clear the circumstances under which it comes up.  I will compose a message to @christinaholtNOAA describing the error and a suggested fix in case it comes up again.

2020-10-26 08:23 UTC, merged

2020-10-26 13:56 UTC, christinaholtNOAA commented
I'm finding this bit of code in the conda.sh file that is sourced:

```
    # We're not allowing PS1 to be unbound. It must at least be set.
    # However, we're not exporting it, which can cause problems when starting a second shell
    # via a first shell (i.e. starting zsh from bash).
    if [ -z "${PS1+x}" ]; then
        PS1=
    fi
```

I'm guessing that has something to do with it. Since I'm not sure how this differs from Jet/Hera at this point, I will have to dig in a bit more later.