Remove several deprecated grids
NOAA-EMC/regional_workflow pull request #342
Opened 2020-10-27 22:52 UTC by gsketefian

## DESCRIPTION OF CHANGES: 
* Rename the GSD_HAFS grids to include underscores (from GSD_HAVSV0.A3km, GSD_HAVSV0.A13km, and GSD_HAVSV0.A25km to GSD_HAVSV0.A_3km, GSD_HAVSV0.A_13km and GSD_HAVSV0.A_25km, respectively).
* Remove grids EMC_CONUS_3km and EMC_CONUS_coarse since the grids CONUS_3km_GFDLgrid and CONUS_25km_GFDLgrid are very similar to these.
* Remove WE2E tests involving the EMC_CONUS_3km and EMC_CONUS_coarse grids (names of removed tests are nco_EMC_CONUS_3km, nco_EMC_CONUS_coarse, and nco_EMC_CONUS_coarse__suite_FV3_GFS_2017_gfdlmp).
* Modify the WE2E test nco_ensemble to use the CONUS_25km_GFDLgrid grid instead of EMC_CONUS_coarse.
* Add new WE2E test nco_CONUS_25km_GFDLgrid to test this grid in NCO mode.  (This test is a replacement for the removed test nco_EMC_CONUS_coarse.)
* Rename all WE2E test configuration files containing the strings "RAPX" and "HRRRX" so that they are replaced with "RAP" and "HRRR", respectively. 
* Update the list of WE2E tests in baselines_list.txt.
* Update the sample NCO-mode workflow configuration file config.nco.sh to:
  a) Use the CONUS_25km_GFDLgrid grid instead of EMC_CONUS_coarse.
  b) Use the FV3_GFS_v15p2 physics suite (which is one of the two supported by the release) instead of FV3_GFS_2017_gfdlmp.
  c) Remove commented-out code.
* Reorder the remaining grids in the case-statement in set_predef_grid_params.sh and in valid_param_vals.sh.

## TESTS CONDUCTED:
On Hera, ran the following tests:
* The renamed test grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_RRFS_v1beta.  This is to make sure that the RAPX,HRRRX --> RAP,HRRR changes did not introduce bugs.
* The existing test nco_ensemble.  This is to make sure that the change in grid in this test didn't break this test.
* The existing test grid_CONUS_25km_GFDLgrid_FV3GFS_FV3GFS to make sure it still works and to generate grid, orography, and surface climatology files for the new test nco_CONUS_25km_GFDLgrid (which uses pregenerated such files).
* The new test nco_CONUS_25km_GFDLgrid.  

All tests were successful.  Also used the sample NCO-mode workflow configuration file config.nco.sh to manually (i.e. without using cron) run a test, which was successful.

2020-10-28 01:05 UTC, JeffBeck-NOAA commented
@gsketefian, we still need the GSD_HAFSV0.A3km pre-defined domain to test GSL physics over the HAFS maritime environment for potential use in the future.

2020-10-28 01:09 UTC, JeffBeck-NOAA commented
> GSD_HAFSV0.A3km

Probably a good time to make it GSL_HAFSV0.A_3km instead of GSD_HAFSV0.A3km.

2020-10-28 01:11 UTC, JeffBeck-NOAA requested changes

2020-10-28 01:11 UTC, JeffBeck-NOAA commented on ush/valid_param_vals.sh
>  "GSD_RAP13km" \
I thought we were going to get rid of the 50-km Alaska grid?  Also, @BenjaminBlake-NOAA, do you mind providing the RRFS_NA_3km ESG grid parameters to @gsketefian?  We can then replace the GSD_RAP13km with that.  Thanks!

2020-10-28 12:16 UTC, BenjaminBlake-NOAA commented on ush/valid_param_vals.sh
>  "GSD_RAP13km" \
@gsketefian Here are the parameters I used to create the RRFS_NA_3km ESG grid.  Let me know if I can provide any more information.

    DT_ATMOS="40"

    LAYOUT_X="20"
    LAYOUT_Y="30"
    BLOCKSIZE="13"
    JPgrid_LON_CTR=-107.5
    JPgrid_LAT_CTR=51.5

    JPgrid_DELX="3000.0"
    JPgrid_DELY="3000.0"

    JPgrid_NX=3640
    JPgrid_NY=2520

    JPgrid_WIDE_HALO_WIDTH=6

2020-10-28 15:58 UTC, gsketefian commented on ush/valid_param_vals.sh
>  "GSD_RAP13km" \
@JeffBeck-NOAA GSD_HRRR_AK_50km is the only Alaska grid that works (sort of), so I want to keep it for testing until we get the other Alaska grids debugged (the RRFS_AK_13km and RRFS_AK_3km fail; see #305).  

@BenjaminBlake-NOAA Is there also a 13km version of the North America grid for testing?  The 3km is rarely going to be run during testing since it is so large.

2020-10-28 15:59 UTC, gsketefian commented
> > GSD_HAFSV0.A3km
> 
> Probably a good time to make it GSL_HAFSV0.A_3km instead of GSD_HAFSV0.A3km.

I removed all the HAFS grids since I thought that's what we agreed to in the email thread.  I can add this back if you want.

2020-10-28 16:09 UTC, BenjaminBlake-NOAA commented on ush/valid_param_vals.sh
>  "GSD_RAP13km" \
@gsketefian Unfortunately we do not have a 13-km version set up at the moment but I agree that the 3-km is too large to include in the regular testing

2020-10-28 16:14 UTC, gsketefian commented on ush/valid_param_vals.sh
>  "GSD_RAP13km" \
@BenjaminBlake-NOAA I am making one now just by reducing nx and ny each by the factor 13/3.

For the 3km grid, do you know why LAYOUT_X (20) is chosen to be smaller than LAYOUT_Y (30) even though JPgrid_NX (3640) is larger than JPgrid_NY (2520)?

2020-10-28 16:25 UTC, BenjaminBlake-NOAA commented on ush/valid_param_vals.sh
>  "GSD_RAP13km" \
@gsketefian Ok sounds good.

I do not have a good reason for why those values were chosen.  For our model runs we are currently using a 40 x 45 layout with this grid

2020-10-28 19:26 UTC, JeffBeck-NOAA commented
> > > GSD_HAFSV0.A3km
> > 
> > 
> > Probably a good time to make it GSL_HAFSV0.A_3km instead of GSD_HAFSV0.A3km.
> 
> I removed all the HAFS grids since I thought that's what we agreed to in the email thread. I can add this back if you want.

Yeah, we need at least one HAFS domain.  From Curtis' email: "We also need an ESG 3-km Alaskan grid as well as a few other OCONUS 3-km ESG grids including a HAFS option".  

And from some guy named Gerard: "Finally, the HAFS grids -- I think Jeff and Curtis were doing some experiments with these grids, but I'm not sure where that work stands.  I know in the long run we want to have a unified physics suite that works for mostly land domains as well as over the ocean, so we'd need these grids for testing over the ocean."

So, at least the 3-km HAFS domain we have in there will need to stay.

2020-10-28 19:30 UTC, JeffBeck-NOAA commented on ush/valid_param_vals.sh
>  "GSD_RAP13km" \
> @JeffBeck-NOAA GSD_HRRR_AK_50km is the only Alaska grid that works (sort of), so I want to keep it for testing until we get the other Alaska grids debugged (the RRFS_AK_13km and RRFS_AK_3km fail; see #305).
> 
> @BenjaminBlake-NOAA Is there also a 13km version of the North America grid for testing? The 3km is rarely going to be run during testing since it is so large.

@gsketefian, OK, I thought there was a problem with either chgres_cube or EMC_post with the 50-km grid points being too coarse, but I could be wrong.  I'd prefer we switch only have the 3- or 13-km Alaska grid, instead, but I guess we'll wait on that.

2020-10-28 19:48 UTC, gsketefian commented on ush/valid_param_vals.sh
>  "GSD_RAP13km" \
@JeffBeck-NOAA Yeah, I'm being conservative and doing only some grid-related fixes per PR.  We eventually got the 50km grid to work with chgres_cube, but I think it now fails in the run_fcst task.  Before I get rid of it, I need to rerun all the AK grids and see which fails on which task.  I'll do that in another PR, probably after the PR.  And I'll need Trevor's and your help on it, probably, since the errors tend to be cryptic.

2020-10-28 19:50 UTC, gsketefian commented
> > > > GSD_HAFSV0.A3km
> > > 
> > > 
> > > Probably a good time to make it GSL_HAFSV0.A_3km instead of GSD_HAFSV0.A3km.
> > 
> > 
> > I removed all the HAFS grids since I thought that's what we agreed to in the email thread. I can add this back if you want.
> 
> Yeah, we need at least one HAFS domain. From Curtis' email: "We also need an ESG 3-km Alaskan grid as well as a few other OCONUS 3-km ESG grids including a HAFS option".
> 
> And from some guy named Gerard: "Finally, the HAFS grids -- I think Jeff and Curtis were doing some experiments with these grids, but I'm not sure where that work stands. I know in the long run we want to have a unified physics suite that works for mostly land domains as well as over the ocean, so we'd need these grids for testing over the ocean."
> 
> So, at least the 3-km HAFS domain we have in there will need to stay.

Don't listen to that Gerard guy.  He's usually talking out of his...!!  

I'll put the 3km one back in and rename it.  Do you want any coarser HAFS grids for testing, or should be worry about that later?

2020-10-28 19:57 UTC, JeffBeck-NOAA commented
> > > > > GSD_HAFSV0.A3km
> > > > 
> > > > 
> > > > Probably a good time to make it GSL_HAFSV0.A_3km instead of GSD_HAFSV0.A3km.
> > > 
> > > 
> > > I removed all the HAFS grids since I thought that's what we agreed to in the email thread. I can add this back if you want.
> > 
> > 
> > Yeah, we need at least one HAFS domain. From Curtis' email: "We also need an ESG 3-km Alaskan grid as well as a few other OCONUS 3-km ESG grids including a HAFS option".
> > And from some guy named Gerard: "Finally, the HAFS grids -- I think Jeff and Curtis were doing some experiments with these grids, but I'm not sure where that work stands. I know in the long run we want to have a unified physics suite that works for mostly land domains as well as over the ocean, so we'd need these grids for testing over the ocean."
> > So, at least the 3-km HAFS domain we have in there will need to stay.
> 
> Don't listen to that Gerard guy. He's usually talking out of his...!!
> 
> I'll put the 3km one back in and rename it. Do you want any coarser HAFS grids for testing, or should be worry about that later?

Lol, sounds good!  It might be good to have a coarser 13-km HAFS domain for future testing, but we can worry about that in a future PR if we want to pull it back in.  For now, I've only been testing at 3-km.

2020-10-28 21:25 UTC, gsketefian commented on ush/valid_param_vals.sh
>  "GSD_RAP13km" \
@JeffBeck-NOAA @BenjaminBlake-NOAA I tried running on both the 3km and 13km NA grids.  The 3km failed in the make_ics/make_lbcs tasks while the 13km failed in the post tasks.  Since this PR is for removing grids (see title) and in order not to delay it, I will add the NA grids in a separate PR.

2020-10-29 22:21 UTC, gsketefian commented
@JeffBeck-NOAA This is ready to be re-reviewed.  Thanks.

2020-10-29 22:52 UTC, JeffBeck-NOAA approved these changes

2020-11-03 23:00 UTC, merged