Add the RRFS_v1alpha suite
NOAA-EMC/regional_workflow pull request #361
Opened 2020-11-11 08:24 UTC by gsketefian

This PR should be merged at the same time as PR #[51](https://github.com/ufs-community/ufs-srweather-app/pull/51) into ufs-srweather-app:release/public-v1 branch as well as a PR into the FV3atm repo that adds a suite definition file for the RRFS_v1alpha suite.

## DESCRIPTION OF CHANGES: 
Add the new suite RRFS_v1alpha to the workflow.  This suite is identical to the RRFS_v1beta suite except that the MYNN surface layer parameterization is replaced with the GFS one.  This entails the following changes:
1) Add the name of the new suite to the list of valid suite names in ush/valid_param_vals.sh.
2) Add a stanza for this suite in ush/templates/FV3.input.yml.
3) Add a diag_table for this suite.
4) Add a field_table for this suite.
5) Add the new suite to the if-statements in the ex-scripts for the make_ics and make_lbcs tasks.
6) Add a workflow end-to-end test for the new suite.

## TESTS CONDUCTED: 
WE2E tests were run with this new suite on the 25km, 13km, and 3km RRFS_CONUS grids.  The tests were run on both the current versions of these grids as well as the new ones that PR #360 introduces (which have NX and NY values that are not evenly divisible by LAYOUT_X and LAYOUT_Y).  All six tests were successful.

## CONTRIBUTORS (optional): 
@climbfuji @JacobCarley-NOAA

2020-11-11 17:51 UTC, JeffBeck-NOAA approved these changes
Looks good!

2020-12-03 20:33 UTC, JeffBeck-NOAA requested changes

2020-12-03 20:33 UTC, JeffBeck-NOAA commented on ush/templates/FV3.input.yml
@gsketefian, Dom's [PR](https://github.com/NOAA-EMC/fv3atm/pull/207#event-4065342034) to add the RRFS_v1alpha SDF, which will be merged soon, includes a requirement for "effr_in" to be defined in the namelist.  Therefore, can you add "effr_in: False" to the list of settings here for FV3_RRFS_v1alpha?  Thanks.

2020-12-03 20:38 UTC, climbfuji commented on ush/templates/FV3.input.yml
Will that be set `.true.` for Thompson MP? That is a requirement. GFS v15p2 I believe uses `.false.`, GFS v16 `.true.` (but need to double check that one)

2020-12-03 20:39 UTC, JeffBeck-NOAA commented on ush/templates/FV3.input.yml
My mistake, it should have been effr_in: True.  Thanks, @climbfuji!

2020-12-04 21:36 UTC, gsketefian commented on ush/templates/FV3.input.yml
@climbfuji I first mistakenly set effr_in to False for the RRFS_v1alpha suite.  The forecast model log file had the (correct) message:
`Thompson MP requires effr_in to be set to .true. - job aborted
`
but the forecast job didn't actually abort; it keeps on going until it runs out of wallclock.  Can we fix this so we don't waste core-hours?  Thx.

2020-12-04 21:40 UTC, climbfuji commented on ush/templates/FV3.input.yml
I don't think that's on my end. The "stop" is the same as for any other exception in `GFS_typedefs.F90`. I remember vaguely that @tanyasmirnova had issues with slurm not aborting a job correctly when slurm was introduced, and that the sysadmins gave her a solution/workaround.

2020-12-04 21:55 UTC, gsketefian commented
@climbfuji @JeffBeck-NOAA I just noticed in our yaml input namelist configuration file that effr_in for the following suites is set to True:

FV3_CPT_v0
FV3_GFS_2017_gfdlmp
FV3_GFS_2017_gfdlmp_regional
FV3_GFS_v16beta

I believe none of these use Thompson mp.  Does that mean this is an error and these should be reset to False, or is there another reason to set these to True?

2020-12-04 21:57 UTC, climbfuji commented
It doesn't mean it is an error. gfdlmp also has effr_in, it used to be .false. in gfs v15p2, but I think it is true for gfs v16 - please check against the operational namelist!

> On Dec 4, 2020, at 2:55 PM, gsketefian <notifications@github.com> wrote:
> 
> 
> @climbfuji <https://github.com/climbfuji> @JeffBeck-NOAA <https://github.com/JeffBeck-NOAA> I just noticed in our yaml input namelist configuration file that effr_in for the following suites is set to True:
> 
> FV3_CPT_v0
> FV3_GFS_2017_gfdlmp
> FV3_GFS_2017_gfdlmp_regional
> FV3_GFS_v16beta
> 
> I believe none of these use Thompson mp. Does that mean this is an error and these should be reset to False, or is there another reason to set these to True?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/NOAA-EMC/regional_workflow/pull/361#issuecomment-739042180>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AB5C2RPRHAOY725QZH447LLSTFLFJANCNFSM4TRWF4MQ>.
>

2020-12-04 22:12 UTC, gsketefian commented
@climbfuji Ok, thanks.  I am checking with Eric Aligo.

2020-12-05 03:52 UTC, JeffBeck-NOAA approved these changes

2020-12-08 02:59 UTC, merged