Add the FV3_HRRR suite to the workflow.
NOAA-EMC/regional_workflow pull request #382
Opened 2020-12-24 13:01 UTC by gsketefian

## DESCRIPTION OF CHANGES: 

### Main changes:
* Add the FV3_HRRR suite to the workflow.  This consists of:
  * Adding "FV3_HRRR" to the list of valid values of CCPP_PHYS_SUITE in valid_param_vals.sh.
  * Adding the diag_table.FV3_HRRR and field_table.FV3_HRRR files to the ush/templates directory. 
  * Adding the FV3_HRRR suite to the case- and if-statements in exregional_make_ics.sh and exregional_make_lbcs.sh.
  * Add a stanza to FV3.input.yml to customize the FV3 namelist file for the FV3_HRRR suite.
* Add WE2E tests for the FV3_HRRR suite on the 25km, 13km, and 3km RRFS_CONUS grids.  These are initialized for the 2020 derecho case (2020081000).  They are named as follows:
  * grid_RRFS_CONUS_25km_ics_HRRR_lbcs_RAP_suite_HRRR
  * grid_RRFS_CONUS_13km_ics_HRRR_lbcs_RAP_suite_HRRR
  * grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_HRRR
* Enable the workflow to find and copy to the experiment directory the pregenerated (for a given grid) orography statistics files ${CRES}_oro_data_ls.tile7.halo0.nc and ${CRES}_oro_data_ss.tile7.halo0.nc needed by the gravity wave drag parameterization in FV3_HRRR.  (Note that this is a temporary fix.  Eventually, a program will be made available that the make_orog task can call to generate these files as part of the workflow for any grid.)  Modifications for this purpose consist of:
  * Adding to config_defaults.sh the new workflow variable GWD_HRRRsuite_BASEDIR that specifies the base directory in which the aformentioned "ls" and "ss" orography statistics files are located for the predefined grid being used.  This workflow variable will be removed once a program is available to generate the "ls" and "ss" files on-the-fly for any grid.
  * Adding to setup.sh code that sets the new derived/secondary workflow variable GWD_HRRRsuite_DIR that specifies the directory in which the "ls" and "ss" files are located (as opposed to just the base directory, which is what GWD_HRRRsuite_BASEDIR represents).  This is set using GWD_HRRRsuite_BASEDIR and PREDEF_GRID_NAME.  Like GWD_HRRRsuite_BASEDIR, this variable will be removed once a program is available to generate the "ls" and "ss" files on-the-fly for any grid.
  * Adding to link_fix.sh code to create symlinks in the fv3_lam directory that point to the "ls" and "ss" files in OROG_DIR. 
  * Adding to exregregional_make_orog.sh code to copy the "ls" and "ss" files from the directory specified by GWD_HRRRsuite_DIR to the orography directory (OROG_DIR).  This code will evenutally be replaced by a call to a program that will generate these files and place them in OROG_DIR (instead of copying them).
  * Adding to exregregional_run_fcst.sh code to create links in the run directory to the"ls" and "ss" orography files that the FV3 model looks for.
  * Adding to run_experiments.sh code to set GWD_HRRRsuite_BASEDIR in the workflow configuration file (config.sh) to the base directory in which the pregenerated "ls" and "ss" orography files are located.  Note that this setting is machine-dependent.
* Change DT_ATMOS for the RRFS_CONUS_25km grid from 300sec to 40sec in order to get this grid to work with the FV3_HRRR suite.

### Improvements:
* Edit error messages in exregional_make_ics.sh and exregional_make_lbcs.sh to make them clearer.
* Correct code indentation and remove blank lines.
* Clean up comments.

## TESTS CONDUCTED: 
Ran the 3 new WE2E tests with the FV3_HRRR suite on (newest versions of) the 25km, 13km, and 3km CONUS grids on Hera, but with the modification that they run for 36 hours instead of just 6 hours.  All three tests were successful.  

## CONTRIBUTORS (optional): 
@toy

2020-12-24 19:09 UTC, JeffBeck-NOAA requested changes

2020-12-24 19:09 UTC, JeffBeck-NOAA commented on scripts/exregional_make_ics.sh
> +    print_err_msg_exit "\
@gsketefian, thanks for adding these print statements for undefined IC/CCPP combinations.  In this stanza, it would probably be better to say "A determination of whether the variable "thomp_mp_climo_file" should be defined for the chosen IC/CCPP combination has not yet been made" or something similar to that.

2020-12-24 19:09 UTC, JeffBeck-NOAA commented on scripts/exregional_make_lbcs.sh
>      print_err_msg_exit "\
Same comment as for undefined IC/CCPP combinations.

2020-12-24 19:09 UTC, JeffBeck-NOAA commented on scripts/exregional_make_lbcs.sh
>      print_err_msg_exit "\
Same comment as undefined IC/CCPP combinations.

2020-12-24 19:09 UTC, JeffBeck-NOAA commented on scripts/exregional_make_lbcs.sh
>      print_err_msg_exit "\
Same comment here too.

2021-01-06 17:51 UTC, JeffBeck-NOAA approved these changes

2021-01-08 14:41 UTC, christinaholtNOAA commented on scripts/exregional_make_ics.sh
> +     [ "${CCPP_PHYS_SUITE}" = "FV3_HRRR" ]; then
We learned in our recent RRFS_dev4 tests that FV3_HRRR should have nsoill_out=9 for both RAP and HRRR ICS and LBCS.

2021-01-08 14:41 UTC, christinaholtNOAA commented on scripts/exregional_make_ics.sh
> +     [ "${CCPP_PHYS_SUITE}" = "FV3_HRRR" ]; then
FV3_HRRR should be in elif.

2021-01-08 14:41 UTC, christinaholtNOAA commented on tests/baselines_list.txt
> +grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_HRRR
Are these tests expected to pass? Does develop have an appropriate tag of the model to run them successfully?

2021-01-08 14:41 UTC, christinaholtNOAA commented on ush/templates/FV3.input.yml
> +
The settings you've added here are very different from those we use in AVID.

2021-01-08 18:12 UTC, gsketefian commented on scripts/exregional_make_ics.sh
> +     [ "${CCPP_PHYS_SUITE}" = "FV3_HRRR" ]; then
Ok, will change.

2021-01-08 18:12 UTC, gsketefian commented on scripts/exregional_make_ics.sh
> +     [ "${CCPP_PHYS_SUITE}" = "FV3_HRRR" ]; then
Ok, will change.

2021-01-08 18:26 UTC, gsketefian commented on tests/baselines_list.txt
> +grid_RRFS_CONUS_3km_ics_HRRR_lbcs_RAP_suite_HRRR
Once I make the FV3 namelist mods and the nsoill_out = 9 fix in the chgres_cube namelist, I will rerun these tests (and others) with the HEADS of both the ufs-community and NOAA-GSL repos.  If the tests pass, then we're good and can merge.  If one or both codes fail, then I may merge this PR anyway but with the FV3_HRRR suite turned off (by removing it from valid_param_vals.sh) just so we can get most of the FV3_HRRR suite script infrastructure in and the work doesn't get wasted.

2021-01-08 18:27 UTC, gsketefian commented on ush/templates/FV3.input.yml
> +
I will change these as you specified in your email and rerun the tests.  Thanks.

2021-01-21 00:19 UTC, christinaholtNOAA approved these changes
This looks functional, but I did leave a few comments related to duplication of information and the need to over-engineer the namelist setting for kice.

2021-01-21 00:19 UTC, christinaholtNOAA commented on scripts/exregional_make_ics.sh
> +     [ "${CCPP_PHYS_SUITE}" = "FV3_HRRR" ]; then
This did not change with the most recent pushes.

2021-01-21 00:19 UTC, christinaholtNOAA commented on scripts/exregional_make_ics.sh
> +     [ "${CCPP_PHYS_SUITE}" = "FV3_HRRR" ]; then
Same here.

2021-01-21 00:19 UTC, christinaholtNOAA commented on ush/generate_FV3LAM_wflow.sh
> +fi
Setting kice really should be a part of FV3.input.yml for the suites that use RUC LSM, no?

2021-01-21 00:19 UTC, christinaholtNOAA commented on ush/link_fix.sh
> +    fi
Why is this information repeated here? Wasn't it handled in an ex-script?

2021-01-21 00:19 UTC, christinaholtNOAA commented on ush/templates/FV3.input.yml
> +# includes RUC-LSM.
Is FV3_HRRR available in the community develop branch at all?

2021-01-21 17:24 UTC, gsketefian commented
@christinaholtNOAA This is actually not the final version of this PR.  I was working on Jet and have changes there that still need to be incorporated when Jet is back up tomorrow.  While working on Hera yesterday, I merged the latest develop into this PR and made a couple of other changes .  After I get the Jet changes in, I'll have to retest.

2021-01-21 17:33 UTC, gsketefian commented on ush/link_fix.sh
> +    fi
The new code snippet in exregional_make_orog.sh copies the ls and ss files from the location specified in GWD_HRRRsuite_DIR to the "orog" subdirectory under the experiment directory (OROG_DIR); those copy commands will eventually be replaced by a call to Mike Toy's code to generate the ls and ss files for any grid (instead of copying).  This snippet is adding the ls and ss files to the list of files (in this case in OROG_DIR) to which symlinks will be created in the FIXLAM directory.  

I've been thinking about simplifying the treatment of the preprocessing directories by making GRID_DIR, OROG_DIR, and SFC_CLIMO_DIR all the same, e.g set them all to FIXLAM.  That's already what happens in NCO mode, where these three variables are all set to ${FIXLAM_NCO_BASEDIR}/${PREDEF_GRID_NAME}.  But that would have to be a separate PR.

2021-01-21 17:36 UTC, gsketefian commented on ush/templates/FV3.input.yml
> +# includes RUC-LSM.
Not currently.  This PR is to add it.

2021-01-21 18:00 UTC, gsketefian commented on ush/generate_FV3LAM_wflow.sh
> +fi
Yes, it currently is in this PR, at least for the suites that I know use RUC_LSM.  I added kice=9 to the GSD_SAR and FV3_HRRR suites in FV3.input.yml (see below).  But I think I'm going to change that and set it in this file (as is done in the "settings" variable below) because setting parameters on a suite basis is becoming cumbersome and error prone.  I'm leaning towards doing things on a parameterization basis, i.e. have the workflow check if a certain parameterization is called in the SDF and set variables accordingly.  That way we don't have to keep track of which suite uses which parameterization; the workflow will figure that out for you and set variables accordingly.  

In this case, this code snippet checks whether the SDF is calling the RUC LSM and sets kice accordingly, so we don't have to remember all the suites that use RUC LSM and then make the appropriate changes in FV3.input.yml.  (For example, I can't say I'm sure that GSD_SAR and FV3_HRRR are the only suites that use RUC LSM; I have to go check the SDFs.)  For other variables like thompson_mp_climo_file and nsoill_out in exregional_make_ics.sh and exregional_make_lbcs.sh, this parameterization-based approach will eliminate the need to have the long if-statements in those scripts (repeated several times in each file, no less).  This way, any changes to these parameterization-dependent variables can be made in one place instead of a bunch of places in several scripts.

Actually, there is already a file in the workflow that does this -- set_thompson_mp_fix_files.sh.  So the idea is to do something analogous for other parameterizations, as needed.

2021-01-21 19:08 UTC, gsketefian commented on scripts/exregional_make_ics.sh
> +     [ "${CCPP_PHYS_SUITE}" = "FV3_HRRR" ]; then
As above, I'm seeing the correct version.  Try reloading the page.  Github has marked this comment as "outdated".

2021-01-27 12:21 UTC, merged

2021-01-30 04:53 UTC, JeffBeck-NOAA commented on ush/generate_FV3LAM_wflow.sh
>  #
Yep, I'd agree that defining lsoil and lsm can be handled because on functions such as "SDF_USES_RUC_LSM".  It would remove the potential for errors in the YAML file or input.nml template.

2021-01-30 04:58 UTC, JeffBeck-NOAA commented
@gsketefian, thoroughly reviewed this PR again. Looks good to me.