release/public-v1: Fix to run workflow tasks on WCOSS Dell and Cray
NOAA-EMC/regional_workflow pull request #385
Opened 2021-01-02 15:52 UTC by chan-hoo

## DESCRIPTION OF CHANGES: 
- Removed the '--relative' flag for the symlink command in multiple scripts only for WCOSS Cray.
- Updated the module file list for each task in 'modulefiles/tasks/wcoss_[dell_p3/cray]'.
- Added separate template xml files for WCOSS Dell or Cray ('FV3LAM_wflow_wcoss_[dell_p3/cray].xml') to the template directory.
- Modified the 'ush/launch_FV3LAM_wflow.sh' script for WCOSS Dell and Cray.
- Added baseline config files to the '/tests/baseline_configs' directory.

## TESTS CONDUCTED: 
- The build-environment file ('README_wcoss_[dell_p3/cray].txt') will be added to SRW App (https://github.com/ufs-community/ufs-srweather-app/issues/79).
- Use the sample config scripts 'config.community_wcoss_[dell_p3/cray].sh' added to '/tests/baseline_configs/'.
- Tested it on WCOSS Dell and Cray with the sample case described in 'config.community.sh'.
- It worked without any issues on WCOSS Dell and Cray. 

## ISSUE: 
Fixes issue mentioned in #384
Related to https://github.com/ufs-community/ufs-srweather-app/issues/79

## CONTRIBUTORS: 
@BenjaminBlake-NOAA

2021-01-04 18:05 UTC, gsketefian commented on scripts/exregional_run_fcst.sh
> +if [ "${RUN_TASK_MAKE_GRID}" = "TRUE" ] && [ "${MACHINE}" != "WCOSS_CRAY" ]; then
On WCOSS_CRAY, what is the equivalent of the "--relative" flag to the ln command?  There must be one...  We can use that instead of leaving relative_or_null set to a null string.  That way, the behavior of the workflow will be the same on all machines.

2021-01-04 18:10 UTC, chan-hoo commented on scripts/exregional_run_fcst.sh
> +if [ "${RUN_TASK_MAKE_GRID}" = "TRUE" ] && [ "${MACHINE}" != "WCOSS_CRAY" ]; then
@gsketefian, since WCOSS_CRAY is running an old version of SuSE Linux (v11.3 or v11.4) which sits on an old version of the Linux kernel, it does not support the "--relative" flag of the symlink command.

2021-01-04 18:10 UTC, BenjaminBlake-NOAA commented on scripts/exregional_run_fcst.sh
> +if [ "${RUN_TASK_MAKE_GRID}" = "TRUE" ] && [ "${MACHINE}" != "WCOSS_CRAY" ]; then
@gsketefian  According to @RatkoVasic-NOAA , the Cray uses the 2011 version of the ln command which does not have the "--relative" capability.  I'm not sure what the equivalent would be - Ratko do you know?

2021-01-04 18:24 UTC, gsketefian commented on ush/templates/FV3LAM_wflow_wcoss_cray.xml
> +{#
Instead of creating a new template xml file for WCOSS_CRAY, I think you can use a jinja2 if-statement to add the <shared/> line (code not tested though!):
```
{% if machine in ["WCOSS_CRAY"]  %}
    <shared/>
{% endif %}
```
Also see line 356 in FV3LAM_wflow.xml.

2021-01-04 18:41 UTC, gsketefian commented on scripts/exregional_run_fcst.sh
> +
Instead of making this change here, it might be better to change PE_MEMBER01 in setup.sh, around line 1864.  That way the correct value for PE_MEMBER01 (i.e. the value actually used in the aprun command) will be recorded in var_defns.sh.  So on line 1864 of setup.sh, add something like this (code untested!):
```
if [ "$MACHINE" -eq "WCOSS_CRAY" ] && [ ${PE_MEMBER01} -lt 24 ]; then
  PE_MEMBER01=24
fi
```

2021-01-04 18:54 UTC, gsketefian commented on scripts/exregional_run_fcst.sh
> +if [ "${RUN_TASK_MAKE_GRID}" = "TRUE" ] && [ "${MACHINE}" != "WCOSS_CRAY" ]; then
@chan-hoo @BenjaminBlake-NOAA @RatkoVasic-NOAA If there is a way to make relative links on WCOSS_CRAY, it would be nice to use it so that the symlinks are to locations within the experiment directory (so they're independent of the root directory of the system).  Otherwise, no big deal.

2021-01-04 19:00 UTC, gsketefian commented on tests/baseline_configs/config.community_wcoss_dell_p3.sh
> +GRID_GEN_METHOD="ESGgrid"
Don't need this line for GRID_GEN_METHOD because now, that is determined by PREDEF_GRID_NAME (i.e. it is part of the definition of the predefined grid).  You only need to set GRID_GEN_METHOD if you're specifying a new grid in config.sh.

2021-01-04 19:01 UTC, gsketefian commented on tests/baseline_configs/config.community_wcoss_dell_p3.sh
> +WFLOW_XML_FN="FV3LAM_wflow_wcoss_dell_p3.xml"
You won't need this line if my suggestion about using a jinja2 if-statement in FV3LAM_wflow.xml works (instead of creating new XML templates).

2021-01-04 19:04 UTC, chan-hoo commented on ush/templates/FV3LAM_wflow_wcoss_cray.xml
> +{#
@gsketefian, I'll modify the scripts (including others below), and then test the feature branch again.

2021-01-04 19:13 UTC, gsketefian commented on tests/baseline_configs/config.community_wcoss_dell_p3.sh
> +USE_USER_STAGED_EXTRN_FILES="FALSE"
If you have this set to "FALSE", then the variables below (e.g. EXTRN_MDL_SOURCE_BASEDIR_ICS) will not be used.  Do you want to use staged files for this test?

The way I handle user-staged external files in the WE2E tests is to set USE_USER_STAGED_EXTRN_FILES to "TRUE" here in the configuration file and then have the WE2E testing script run_experiment.sh check for the value of USE_USER_STAGED_EXTRN_FILES (starting around line 671).  If it is set to "TRUE" (which it will be), then run_experiments.sh will add to the configuration file appropriate (i.e. machine-dependent) values for the remaining variables such as EXTRN_MDL_SOURCE_BASEDIR_ICS.  See, for example, the file 
`regional_workflow/tests/config.grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2.sh
`
Note that all the WE2E tests are meant to be run using the run_experiments.sh script.  That script will take your config.some_test_name.sh file and create from it a final config.sh file that contains all the necessary variables.  Once you call run_experiments.sh and the experiment directory for your WE2E test is created, a copy of that final config.sh can be found in that experiment directory.

So, in summary, if you want to use user-staged external files for this test, you can set USE_USER_STAGED_EXTRN_FILES to "TRUE" here and then set the remaining variables below in run_experiments.sh.

2021-01-04 19:16 UTC, gsketefian commented on tests/baseline_configs/config.community_wcoss_cray.sh
> +RUN_ENVIR="community"
See my comments for config.community_wcoss_dell_p3.sh.  Same comments apply to this file.

2021-01-04 21:53 UTC, chan-hoo commented on tests/baseline_configs/config.community_wcoss_dell_p3.sh
> +GRID_GEN_METHOD="ESGgrid"
@gsketefian, I removed two cases for wcoss here. Since wcoss does not use separate templates, I think we don't need sample cases for wcoss any more.

2021-01-04 21:53 UTC, chan-hoo commented on tests/baseline_configs/config.community_wcoss_dell_p3.sh
> +WFLOW_XML_FN="FV3LAM_wflow_wcoss_dell_p3.xml"
removed.

2021-01-04 21:53 UTC, chan-hoo commented on tests/baseline_configs/config.community_wcoss_dell_p3.sh
> +USE_USER_STAGED_EXTRN_FILES="FALSE"
removed

2021-01-04 21:54 UTC, chan-hoo commented on tests/baseline_configs/config.community_wcoss_cray.sh
> +RUN_ENVIR="community"
removed

2021-01-04 22:28 UTC, gsketefian commented on tests/baselines_list.txt
> +et_extrn_files_from_hpss_FV3GFS_FV3GFS
Typo (missing "g")?

2021-01-04 22:36 UTC, chan-hoo commented on tests/baselines_list.txt
> +et_extrn_files_from_hpss_FV3GFS_FV3GFS
Oops! Sorry. Corrected.

2021-01-05 04:55 UTC, JeffBeck-NOAA requested changes
Hi @chan-hoo, we don't have platform-specific config templates in the /ush directory.  Is there a reason the current config.community.sh doesn't work for you?

2021-01-05 05:01 UTC, chan-hoo commented
@JeffBeck-NOAA, that script is just for a test on wcoss. Since I made some changes in several scripts, I need to test this feature branch on the dell and cray again. Once the test is complete, I'll remove this script for wcoss.

2021-01-05 05:22 UTC, JeffBeck-NOAA commented
> @JeffBeck-NOAA, that script is just for a test on wcoss. Since I made some changes in several scripts, I need to test this feature branch on the dell and cray again. Once the test is complete, I'll remove this script for wcoss.

Thanks @chan-hoo!  I saw it was added to the PR, so I was confused.  Thanks for clarifying!

2021-01-05 14:19 UTC, chan-hoo commented on scripts/exregional_run_fcst.sh
> +if [ "${RUN_TASK_MAKE_GRID}" = "TRUE" ] && [ "${MACHINE}" != "WCOSS_CRAY" ]; then
@gsketefian, I couldn't find any other options for this.

2021-01-05 14:20 UTC, chan-hoo commented on ush/templates/FV3LAM_wflow_wcoss_cray.xml
> +{#
Done.

2021-01-05 14:22 UTC, chan-hoo commented on scripts/exregional_run_fcst.sh
> +
@gsketefian, It didn't work for the Cray. It caused other errors. I think this is the best option for the Cray.

2021-01-05 14:33 UTC, chan-hoo commented
@gsketefian @JeffBeck-NOAA , I've tested the modified one. It works well on the wcoss dell and cray. Please review it again.

2021-01-05 16:01 UTC, gsketefian commented on scripts/exregional_run_fcst.sh
> +if [ "${RUN_TASK_MAKE_GRID}" = "TRUE" ] && [ "${MACHINE}" != "WCOSS_CRAY" ]; then
@chan-hoo Ok, no problem.

2021-01-05 16:15 UTC, gsketefian commented on scripts/exregional_run_fcst.sh
> +
Huh, weird.  Ok, if you prefer this, it's ok with me.

2021-01-05 16:33 UTC, gsketefian commented
@chan-hoo This looks good to me.  Couple of things:
1) Can you update the PR message to remove the lines about separate template XMLs and new test config files (since you removed all those)?
2) Can you try running a test on Hera to make sure everything still works there (e.g. to make sure the jinja changes didn't break anything on Hera)?
Thanks.

2021-01-05 17:59 UTC, chan-hoo commented
> @chan-hoo This looks good to me. Couple of things:
> 
> 1. Can you update the PR message to remove the lines about separate template XMLs and new test config files (since you removed all those)?
> 2. Can you try running a test on Hera to make sure everything still works there (e.g. to make sure the jinja changes didn't break anything on Hera)?
>    Thanks.

1. Done.
2. Done without any issues.

2021-01-05 18:17 UTC, gsketefian commented
@chan-hoo Thanks.  I will approve.
@JeffBeck-NOAA Are there changes that you'd still like @chan-hoo to make?  If not, can he merge?

2021-01-05 18:17 UTC, gsketefian approved these changes

2021-01-05 18:30 UTC, JeffBeck-NOAA approved these changes

2021-01-05 18:30 UTC, JeffBeck-NOAA commented
> @chan-hoo Thanks. I will approve.
> @JeffBeck-NOAA Are there changes that you'd still like @chan-hoo to make? If not, can he merge?

@gsketefian, I'm good with everything!  Going to approve.  I'll also merge, since I don't believe @chan-hoo has permissions.

2021-01-05 18:33 UTC, JeffBeck-NOAA commented
@chan-hoo, I added you to the repo with write permission.  Can you try to merge?  Thanks!

2021-01-05 18:37 UTC, merged