Make DT_ATMOS, LAYOUT_X/Y, and BLOCKSIZE user-specifiable when using predefined grids
NOAA-EMC/regional_workflow pull request #396
Opened 2021-01-12 23:52 UTC by gsketefian

## DESCRIPTION OF CHANGES: 
One or more paragraphs describing the problem, solution, and required changes.

## TESTS CONDUCTED: 
Explicitly state what tests were run on these changes, or if any are still pending (for README or other text-only changes, just put "None required". Make note of the compilers used, the platform/machine, and other relevant details as necessary. For more complicated changes, or those resulting in scientific changes, please be explicit!

## ISSUE (optional): 
If this PR is resolving or referencing one or more issues, in this repository or elewhere, list them here. For example, "Fixes issue mentioned in #123" or "Related to bug in https://github.com/NOAA-EMC/other_repository/pull/63"

2021-01-13 17:40 UTC, JeffBeck-NOAA commented on ush/config_defaults.sh
> +#
Isn't the following part of the removed comment still true if PREDEF_GRID_NAME is set to a valid grid: "In addition, if the time step DT_ATMOS and the computational parameters LAYOUT_X, LAYOUT_Y, and BLOCKSIZE are not specified in that configuration file, they are also set to predefined values for the specified grid."  Actually, weren't they previously just overwritten by the predefined values if this was the case?

2021-01-13 17:48 UTC, JeffBeck-NOAA commented on ush/config_defaults.sh
> +#
@gsketefian, I thought if the user specifies their own values in config.sh, they should **not** be overwritten?

2021-01-13 17:54 UTC, JeffBeck-NOAA requested changes

2021-01-13 17:54 UTC, JeffBeck-NOAA commented on ush/config_defaults.sh
> +#   file will be used.
If PREDEF_GRID_NAME is an empty string, this implies that the user is running with their own configured grid.  We might want to clarify that here.

2021-01-13 18:35 UTC, gsketefian commented on ush/config_defaults.sh
> +#
By "grid parameters", I mean just those parameters that define the native and write-component grids.  Those can't be overwritten (otherwise there is no point to having a predefined grid).  The way I'm defining "grid parameters" here doesn't include DT_ATMOS, LAYOUT_X/Y, and BLOCKSIZE because the latter are affected by the grid but are technically independent of it.  These four parameters can be overwritten by the user via config.sh.  That's what this PR does.  That's what the "In addition, ..." sentence is trying to say.

2021-01-13 18:44 UTC, gsketefian commented on ush/config_defaults.sh
> +#   file will be used.
Ok, I modified the comment to clarify.  Let me know what you think.

2021-01-13 19:35 UTC, JeffBeck-NOAA approved these changes

2021-01-13 19:35 UTC, JeffBeck-NOAA commented on ush/config_defaults.sh
> +#
OK, thanks for the clarification!

2021-01-13 19:35 UTC, JeffBeck-NOAA commented on ush/config_defaults.sh
> +#   file will be used.
Looks good!

2021-01-13 20:14 UTC, merged

2021-01-14 13:43 UTC, chan-hoo commented
@gsketefian @JeffBeck-NOAA,  I think this change makes setting the grid-specific parameters complicated much more. If DT_ATMOS, LAYOUT_X, LAYOUT_Y, BLOCKSIZE are not specified in 'config.sh', their default values in 'config_default.sh' will be used even though I want to use the values specified in 'set_predef_grid_params.sh'. To make it work, you should remove them from 'config_default.sh'. I tested it without setting them in 'config.sh', but I got the values from 'config_default.sh' (NOT from 'set_predef_grid_params.sh').

2021-01-14 17:31 UTC, JeffBeck-NOAA commented
@gsketefian, following on from @chan-hoo's comment, is this the expected behavior?  I would think that if a pre-defined grid is selected, AND if the user doesn't set anything explicitly in config.sh, the values in set_predef_grid_params.sh would be used, correct?

2021-01-14 17:32 UTC, JeffBeck-NOAA commented
@chan-hoo, when you said you got the values from config_default.sh and not from set_predef_grid_params.sh, can you confirm that you had PREDEF_GRID_NAME defined in your config.sh file?

2021-01-14 17:58 UTC, chan-hoo commented
@JeffBeck-NOAA, yes. I used PREDEF_GRID_NAME="RRFS_CONUS_25km"

2021-01-14 18:05 UTC, JeffBeck-NOAA commented
> @JeffBeck-NOAA, yes. I used PREDEF_GRID_NAME="RRFS_CONUS_25km"

@gsketefian, is this a bug?