Sub-hourly post-processing enabled by some new config.sh entries.
NOAA-EMC/regional_workflow pull request #439
Opened 2021-02-17 20:13 UTC by Jeff-Duda

## DESCRIPTION OF CHANGES: 
Modified the Jinja-formatted FV3LAM_wflow.xml template workflow to accommodate sub-hourly post-processing tasks that rely on sub-hourly FV3 output as a dependency. All changes are _additions_ to existing code and include the addition of a few keyword variables in the config.sh script. These new flags include...

- SUB_HOURLY_POST: a logic flag indicating whether nor not sub-hourly post-processing is to be used
- DELTA_MIN: the increment in minutes to sub-divide the hour

setup.sh was updated to check whether valid entries were used for these two variables and also check that DT_ATMOS divides evenly into DELTA_MIN so that the FV3 output is consistent with the requested frequency of UPP output. config_defaults.sh and valid_param_vals.sh were also updated accordingly. Default config files (config.community.sh and config.nco.sh) were also modified to include these entries for users who may want it right out of the box.

Note that ${dt_atmos} has been added as a yet-unused variable in the post job and script for potential future developments involving processing the very first FV3 output file (done at the end of the first time step rather than at f00:00:00). This may be updated later.

## TESTS CONDUCTED: 
Have run generate_FV3LAM_wflow.sh on a large variety of settings of SUB_HOURLY_POST and DELTA_MIN. Note that setup.sh is configured such that DELTA_MIN = 0 will cause SUB_HOURLY_POST to be ignored. I have successfully tested cases in which DT_ATMOS _does not_ divide evenly into DELTA_MIN and when DELTA_MIN is specified as anything other than a two-digit value (strings vs. open integers both work).

The resulting workflows run successfully with rocotorun and output no error messages.

## ISSUE (optional): 
Resolves issue #434

2021-02-20 07:15 UTC, JeffBeck-NOAA requested changes
@Jeff-Duda, thanks for getting this PR opened!  I took a quick look through and found only minor things so far.   To update a PR, you only need to make changes, commit then, then issue a 'git push' and it will automatically update everything in GitHub.  I'll check out your feature branch next week to run a test without sub-hourly data, but to test with sub-hourly data, I'll need to manually modify the model_configure file.  Therefore, one thing we should add in the future is a user-defined option to automatically set those model_configure parameters for sub-hourly output (leveraging your DELTA_MIN entry should be nearly all that's required to do that, I would think).  If you wanted, you could include that feature in this PR, or we could create a second PR later.  Up to you!

2021-02-20 07:15 UTC, JeffBeck-NOAA commented on scripts/exregional_run_post.sh
> +
I'm guessing lines 298 and 299 were for testing purposes?  If so, can you remove those to limit logging output?  Thanks.

2021-02-20 07:15 UTC, JeffBeck-NOAA commented on jobs/JREGIONAL_RUN_POST
>  #-----------------------------------------------------------------------
Could you rewrite the error statement to follow the "print_err_msg_exit" paradigm (see line 135)?  That's how we handle error-then-exit in the workflow.  I see you used it in later commits, so I'm guessing this may have been one of your first ones!

Also, could you rewrite the comment as:

#-----------------------------------------------------------------------
\#
\# Check if all necessary environmental variables are included.
\# 
#-----------------------------------------------------------------------

Thanks!

2021-02-20 07:15 UTC, JeffBeck-NOAA commented on ush/config.community.sh
Can you set SUB_HOURLY_POST to "FALSE" as the default?  Right now, the hourly output is the standard way we run the SRW App, so users who wish to run sub-hourly can just flip this logical when they copy this file to config.sh.  Thanks.

2021-02-20 07:15 UTC, JeffBeck-NOAA commented on ush/config.nco.sh
Same comment as above.

2021-02-20 07:15 UTC, JeffBeck-NOAA commented on ush/templates/FV3LAM_wflow.xml
> +
Should lines 435-447 be wrapped in an {% if sub_hourly_post %}, {% else %}, {% endif %}, as in lines 411-415?  Otherwise you'd get both dependencies regardless of what SUB_HOURLY_POST is set to?

2021-02-20 07:15 UTC, JeffBeck-NOAA commented on ush/generate_FV3LAM_wflow.sh
>  " # End of "settings" variable.
Any reason 'del_min' can't be 'delta_min'?

2021-02-22 17:22 UTC, Jeff-Duda commented on scripts/exregional_run_post.sh
> +
Correct...I was testing. Removed them.

2021-02-22 17:27 UTC, Jeff-Duda commented on jobs/JREGIONAL_RUN_POST
>  #-----------------------------------------------------------------------
Made requested formatting changes

2021-02-22 17:28 UTC, Jeff-Duda commented on ush/config.community.sh
Made suggested change

2021-02-22 17:28 UTC, Jeff-Duda commented on ush/config.nco.sh
Made suggested change.

2021-02-22 17:29 UTC, Jeff-Duda commented on ush/generate_FV3LAM_wflow.sh
>  " # End of "settings" variable.
Changed del_min to delta_min in this script as well as the FV3LAM_wflow.xml template in templates/

2021-02-22 17:58 UTC, gsketefian commented on jobs/JREGIONAL_RUN_POST
> +fhr_dir="${postprd_dir}/$fhr$fmin"
Can we change "fmin" to something like "fmn"?  The "min" makes me think of "minimum", and "mn" is used in several other places in the scripts for "minutes".  Thanks.

2021-02-22 18:06 UTC, gsketefian commented on jobs/JREGIONAL_RUN_POST
> +if [[ "${fmin}" ]] && [[ ! "${dt_atmos}" ]]; then
For consistency with the rest of the scripts, modify this to:
```
if [ -n "$fmin" ] && [ -z "${dt_atmos}" ]; then
  print_err_msg_exit "\
You set environmental variable \"fmin\" but did not supply \"dt_atmos\"
as well (same as in FV3 namelist). Both of these need to be set so that
UPP will process the correct file for the first output timestep model fields."
fi
```
Note that the "print_err_msg_exit" function will exit the script with a nonzero error code, so there's no need to include a call to "exit 2".

2021-02-22 18:12 UTC, Jeff-Duda commented on ush/templates/FV3LAM_wflow.xml
> +
There is more than one way this can be done.

I went with a suggestion by Christina Holt to engineer this task such that there will _always_ be a set of nested metatasks regardless of whether sub-hourly output was requested. Christina thought that would be more helpful to users in understanding what is going on at the task level in the workflow. The idea is that, when sub-hourly processing is not being used, the workflow <var=fmin> array will just be the single entry "00". Leaving the dependency structure as is would mean the dependencies would always be appropriate no matter whether sub-hourly processing was used or not. But yes, it does result in a <dependency> structure that seems a bit kooky.

If other reviewers feel strongly about adopting your suggestion, that can certainly be done. Let's get the opinions of others, though.

2021-02-22 18:15 UTC, Jeff-Duda commented on jobs/JREGIONAL_RUN_POST
> +fhr_dir="${postprd_dir}/$fhr$fmin"
Changed $fmin to $fmn throughout jobs/JREGIONAL_RUN_POST and scripts/exregional_run_post.sh, but not in the template FV3LAM_wflow file. I feel that in the workflow, the meaning is pretty straightforward and isolated from other usages within the system.

2021-02-22 18:15 UTC, Jeff-Duda commented on jobs/JREGIONAL_RUN_POST
> +if [[ "${fmin}" ]] && [[ ! "${dt_atmos}" ]]; then
Already modified as per Jeff Beck's comments.

2021-02-22 18:22 UTC, gsketefian commented on ush/config.community.sh
> +SUB_HOURLY_POST="TRUE"
Probably don't want to include these in the sample config files (config.community.sh and config.nco.sh) since most people won't be using this feature (not yet at least).

2021-02-22 18:26 UTC, gsketefian commented on ush/config_defaults.sh
> +SUB_HOURLY_POST="FALSE"
Same as above, i.e. remove from this file.

2021-02-22 18:27 UTC, gsketefian commented on ush/config.nco.sh
> +SUB_HOURLY_POST="TRUE"
Same as above, i.e. remove from this file.

2021-02-22 18:29 UTC, Jeff-Duda commented on ush/config.community.sh
> +SUB_HOURLY_POST="TRUE"
Removed DELTA_MIN and SUB_HOURLY_POST from the sample config files.

2021-02-22 18:29 UTC, Jeff-Duda commented on ush/config_defaults.sh
> +SUB_HOURLY_POST="FALSE"
Same as above

2021-02-22 18:29 UTC, Jeff-Duda commented on ush/config.nco.sh
> +SUB_HOURLY_POST="TRUE"
Same as above

2021-02-22 18:30 UTC, gsketefian commented on ush/setup.sh
> +MIN_OR_NULL=$( printf "%s" "${DELTA_MIN}" | \
To follow the convention usually used in the rest of the script, make MIN_OR_NULL lowercase (min_or_null) since it is a local variable.  Usually, global workflow/experiment variables (those that get recorded in var_defns.sh) are uppercase and local variables (those that are used only within a script) are lowercase.

2021-02-22 18:35 UTC, gsketefian commented on ush/config_defaults.sh
> +DELTA_MIN="15"
The "MIN" again threw me off at first because I thought this was some sort of minimum value for a variable named DELTA.  It becomes clear what it is after one looks at the code, but we'd like it to be clearer than that so we pretty much know what it is right when we read it.  So maybe rename to something like DT_SUBHOURLY_POST_MNTS to indicate that it is a time interval (DT), used only when doing subhourly post (SUBHOURLY_POST), and is in units of minutes (MNTS; the workflow uses MNTS elsewhere to indicate units are in minutes).

2021-02-22 18:36 UTC, gsketefian commented on ush/generate_FV3LAM_wflow.sh
> +  'del_min': ${DELTA_MIN}
For clarity, use same variable name (except lowercase) in jinja template as in workflow, i.e. use delta_min instead of del_min.

2021-02-22 18:55 UTC, gsketefian commented on ush/setup.sh
> +else
Three comments here:
1) This check can be a separate if-statement later below (e.g. after the check of BLOCKSIZE) instead of being here as an else-clause.
2) Probably should do this check only if SUB_HOURLY_POST is set to TRUE.  
3) The error message can be clarified to specify that DELTA_MIN (after converting to seconds) must be evenly divisible by DT_ATMOS.

Overall, maybe something like this (note: I haven't tested this):
```
if [ "${SUB_HOURLY_POST}" = "TRUE" ]; then
  rem=$(( (DELTA_MIN*60) % DT_ATMOS ))
  if [ "$rem" -ne "0" ]; then
    print_err_msg_exit "\
When performing sub-hourly post (i.e. SUB_HOURLY_POST set to \"TRUE\"), the time
interval specified by DELTA_MIN (after converting to seconds) must be evenly divisible 
by the time step DT_ATMOS used in the forecast model, i.e. the remainder (rem) must 
be zero.  In this case, it is not:
  SUB_HOURLY_POST = \"${SUB_HOURY_POST}\"
  DELTA_MIN = \"${DELTA_MIN}\"
  DT_ATMOS = \"${DT_ATMOS}\"
  rem = \$(( (DELTA_MIN*60) % DT_ATMOS )) = $rem
Please reset DELTA_MIN and/or DT_ATMOS so that the remainder is zero."
  fi
fi
```

2021-02-22 19:23 UTC, Jeff-Duda commented on ush/setup.sh
> +MIN_OR_NULL=$( printf "%s" "${DELTA_MIN}" | \
I made the requested change, but I do not understand what makes MIN_OR_NULL different from other nearby similar variables such as DATE_OR_NULL or CYCL_OR_NULL that are also in setup.sh and seem to have the same purpose but are in upper-case.

2021-02-22 19:31 UTC, Jeff-Duda commented on ush/config_defaults.sh
> +DELTA_MIN="15"
Changed global variable DELTA_MIN to DT_SUBHOURLY_POST_MNTS throughout

2021-02-22 19:31 UTC, gsketefian commented on scripts/exregional_run_post.sh
> +if [ ! "${fmin}" ]; then
Can reduce repetition and hard-coding by doing something like this:

mnts_secs_str=""
if [ "${SUB_HOURLY_POST}" = "TRUE" ]; then
  if [ ${fhr} = "000" ]; then
    mnts_secs_str=":${fmin}:45"
  else
    mnts_secs_str=":${fmin}:00"
  fi
else
  fmin="00"
fi

dyn_file="${run_dir}/dynf${fhr}${mnts_secs_str}.nc"
phy_file="${run_dir}/phyf${fhr}${mnts_secs_str}.nc"
post_time=$( date --utc --date "${yyyymmdd} ${hh} UTC + ${fhr} hours + ${fmin} minutes" "+%Y%m%d%H%M" )

2021-02-22 19:31 UTC, Jeff-Duda commented on ush/generate_FV3LAM_wflow.sh
> +  'del_min': ${DELTA_MIN}
Done

2021-02-22 19:33 UTC, gsketefian commented on scripts/exregional_run_post.sh
> +elif [ ${len_fmin} -eq 3 ]; then
Under what circumstances is fmin set to something with more than 2 digits?

2021-02-22 19:34 UTC, Jeff-Duda commented on ush/setup.sh
> +else
Made exact suggested changes

2021-02-22 19:36 UTC, gsketefian commented on scripts/exregional_run_post.sh
> +if [[ ! "${fmin}" ]] || [[ ${fmin} -eq 00 ]]; then
With the suggested code above where fmin gets set to "00" if SUB_HOURLY_POST is not set to "TRUE", you don't need this if-statement, just the else part of it, i.e. just use
```
mv_vrfy BGDAWP.GrbF${post_fhr}.${fmin} ${postprd_dir}/${NET}.t${cyc}z.bgdawpf${fhr}${fmin}.${tmmark}.grib2
mv_vrfy BGRD3D.GrbF${post_fhr}.${fmin} ${postprd_dir}/${NET}.t${cyc}z.bgrd3df${fhr}${fmin}.${tmmark}.grib2
```

2021-02-22 19:37 UTC, Jeff-Duda commented on scripts/exregional_run_post.sh
> +if [ ! "${fmin}" ]; then
Made exact suggested change and also changed "45" to ${dt_atmos} (passed in from JREGIONAL_RUN_POST) to reflect actual behavior of FV3 output at forecast hour 0.

2021-02-22 19:37 UTC, gsketefian commented on scripts/exregional_run_post.sh
> +ln_vrfy -fs ${postprd_dir}/${NET}.t${cyc}z.bgdawpf${fhr}00.${tmmark}.grib2 \
Why is the change in the file name here always "00"?  Shouldn't it be "$fmin" in general?

2021-02-22 19:38 UTC, Jeff-Duda commented on scripts/exregional_run_post.sh
> +elif [ ${len_fmin} -eq 3 ]; then
Probably none. I was just absent-mindedly modeling this section off of the one for forecast hour above. I removed that elif block.

2021-02-22 19:42 UTC, Jeff-Duda commented on scripts/exregional_run_post.sh
> +if [[ ! "${fmin}" ]] || [[ ${fmin} -eq 00 ]]; then
Just note that there are instances during which UPP outputs a different file naming structure depending on whether sub-hourly output is requested or not. When no sub-hourly output is requested, the output file name from UPP does not contain the ".${fmn}" syntax. I am not 100% sure how this is yet determined, though. I think it is through the time entry in the itag file, but it might be something different.

As of now, I have removed the if-then statement.

2021-02-22 19:43 UTC, Jeff-Duda commented on scripts/exregional_run_post.sh
> +ln_vrfy -fs ${postprd_dir}/${NET}.t${cyc}z.bgdawpf${fhr}00.${tmmark}.grib2 \
Made suggested change.

2021-02-22 20:11 UTC, gsketefian commented
@Jeff-Duda Can you push your latest changes to your fork so we can see them under the "Files Changed" tab?  Thanks.

2021-02-22 20:20 UTC, Jeff-Duda commented
> 
> 
> @Jeff-Duda Can you push your latest changes to your fork so we can see them under the "Files Changed" tab? Thanks.

@gsketefian I am going to re-run some tests to confirm the changes still work before pushing changes.

2021-02-23 19:45 UTC, Jeff-Duda commented on scripts/exregional_run_post.sh
> +if [[ ! "${fmin}" ]] || [[ ${fmin} -eq 00 ]]; then
Okay, so I can confirm that when the minutes-past-the-hour in the time is "00", UPP outputs a file with a different naming format, so this if statement needs to be there for now.

2021-02-24 22:27 UTC, Jeff-Duda commented
Completed bug fixes as suggested by @JeffBeck-NOAA and @gsketefian. Notes on those changes are addressed for each comment.

Referring back to the original PR request message, the variable ${DT_ATMOS} in exregional_run_post.sh is no longer unused (it is now used to specify the very first FV3 output file). Moreover, ${DT_ATMOS} and ${DT_SUBHOURLY_POST_MNTS} have been added to exregional_run_fcst.sh so that they get into create_model_configure_file.sh to write the model_configure file to produce sub-hourly output from FV3. This set of changes also means that sub-hourly FV3 output can now be enabled by using the same settings as for sub-hourly UPP output, although we may need to re-visit separating those two (note: getting sub-hourly FV3 output is not dependent on the SUB_HOURLY_POST logical flag in the config file, so a user should be able to setup a workflow to enable sub-hourly FV3 output without also performing sub-hourly post-processing.

2021-02-24 22:44 UTC, Jeff-Duda commented on ush/config_defaults.sh
> +SUB_HOURLY_POST="FALSE"
I mis-read this comment the first time around, and thus the first of the new commits (hash f4f7fc568eb57cfce03aa90c89fc19062e5401bf) doesn't actually reflect this comment. But I made a second commit that does include descriptions for these new variables in config_defaults.sh.

2021-02-25 03:48 UTC, JeffBeck-NOAA commented on ush/templates/FV3LAM_wflow.xml
> +
OK, that makes sense.  So the way this is written now, if you run with sub-hourly output, you need all four "phyf#fhr#:#fmin#:{{ dt_atmos }}", "phyf#fhr#:#fmin#:00.nc", "phyf#fhr#:#fmin#:{{ dt_atmos }}", and "phyf#fhr#:#fmin#:00.nc" before the post task will kick off for a combined set of fhr and fmn values?  Otherwise, if it's hourly output, then it operates as before (because you have an <or> in the dependency)?

2021-02-25 03:49 UTC, JeffBeck-NOAA commented on scripts/exregional_run_post.sh
> +ln_vrfy -fs ${postprd_dir}/${NET}.t${cyc}z.bgdawpf${fhr}00.${tmmark}.grib2 \
Do the "00"s in lines 311 and 313 still need to be replaced by ${fmn}?

2021-02-25 03:54 UTC, JeffBeck-NOAA commented on ush/setup.sh
> +else
Have you tested this code block with a value of DT_ATMOS that isn't evenly divisible by DELTA_MIN to ensure you get the new error message?

2021-02-25 16:49 UTC, Jeff-Duda commented on ush/templates/FV3LAM_wflow.xml
> +
Yes, that is correct.

2021-02-25 17:01 UTC, Jeff-Duda commented on ush/setup.sh
> +else
Good call. Yes, the check worked as far as quitting the generate script if an inconsistent set of values was used, but the line 

`rem = \$(( (DELTA_MIN*60) % DT_ATMOS )) = $rem`

was causing a secondary error, so I replaced that with

`rem = ${val}`

and commit-pushed it (commit hash 3621f16c).

2021-02-25 17:02 UTC, Jeff-Duda commented on scripts/exregional_run_post.sh
> +ln_vrfy -fs ${postprd_dir}/${NET}.t${cyc}z.bgdawpf${fhr}00.${tmmark}.grib2 \
Yes. They now have been.

2021-02-26 09:56 UTC, gsketefian commented on scripts/exregional_run_fcst.sh
> +  delta_fmin="${DT_SUBHOURLY_POST_MNTS}" \
To keep consistent with the rest of the variables, change delta_fmin to dt_subhourly_post_mnts.  Thx.

2021-02-26 09:58 UTC, gsketefian commented on scripts/exregional_run_post.sh
> +len_fmin=${#fmn}
Don't need this if-statement because fmn is hard-coded in the template xml to be a 2-digit string.

2021-02-26 10:16 UTC, gsketefian commented on scripts/exregional_run_post.sh
> +len_fmin=${#fmn}
Don't need this if-statement at all since post_fmn is set but not used.

2021-02-26 10:17 UTC, gsketefian commented on scripts/exregional_run_post.sh
> +post_min=${post_time:10:2}
For consistency with the other variables, change post_min to post_mn.

2021-02-26 10:19 UTC, gsketefian commented on scripts/exregional_run_post.sh
> +  mv_vrfy BGDAWP.GrbF${post_fhr}.${fmn} ${postprd_dir}/${NET}.t${cyc}z.bgdawpf${fhr}${fmn}.${tmmark}.grib2
For consistency with what is done with the hours, use post_mn instead of fmn in the BGDAWP and BGRD3D file names.

2021-02-26 10:23 UTC, gsketefian commented on ush/setup.sh
> +  SUB_HOURLY_POST="FALSE"
Can you include an informational message to the user that this variable is being changed from what it was in the user's configuration file (and why)?  Use the print_info_msg function to do that (lots of examples in this and other files of that).  Thanks!

2021-02-26 10:45 UTC, gsketefian commented on ush/setup.sh
> +  rem = ${val}
The problem with this line was probably the percent sign.  Try escaping it by using a double-percent, like this:
`  rem = \$(( (DELTA_MIN*60) %% DT_ATMOS )) = $rem
`
That worked for me.  It would be good to show the formula so the user knows exactly what the calculation being performed is.

2021-02-26 10:53 UTC, gsketefian commented on ush/create_model_configure_file.sh
> +delta_fmin \
For consistency with the rest of the scripts, change delta_fmin to dt_subhourly_post_mnts.  Having the same name for the same variable everywhere in the code comes in handy when grepping all the scripts to find where it's used.

2021-02-26 11:03 UTC, gsketefian commented on ush/create_model_configure_file.sh
> +   ((nsout = delta_fmin*60 / dt_atmos))
For consistency with other arithmetic lines, change to:
`nsout=$(( dt_subhourly_post_mnts*60 / dt_atmos ))`
Actually, this seems to be the same variable as the remainder calculated in setup.sh that has to be zero when doing subourly post; otherwise, setup.sh quits.  Doesn't that mean it will always be zero here?

2021-02-26 11:04 UTC, gsketefian commented on ush/create_model_configure_file.sh
> +  if [ "${sub_hourly_post}" = "TRUE" ]; then
Can you add a comment right above here explaining what nfhout and nsout are?

2021-02-26 11:14 UTC, gsketefian commented on ush/templates/FV3LAM_wflow.xml
> +
Is all this valid when dt_atmos is greater than 59sec?  In that case, do you have to convert some of dt_atmos to minutes?  Say dt_subhourly_post_mnts is 15 minutes (900 sec) and dt_atmos is 90 sec, then the remainder is 0 so the test in setup.sh will pass, but here the file name will be strange -- phyf....90.nc.

2021-02-26 11:17 UTC, gsketefian commented on jobs/JREGIONAL_RUN_POST
> +if [[ "${fmn}" ]] && [[ ! "${DT_ATMOS}" ]]; then
For consistency with other if-statements, change to 
if [ -n "${fmn}" ] && [ -z "${DT_ATMOS}" ]; then

2021-02-26 16:28 UTC, gsketefian commented on ush/config_defaults.sh
> +SUB_HOURLY_POST="FALSE"
Ok, thanks for including those descriptions.

2021-02-26 16:41 UTC, gsketefian commented on scripts/exregional_run_post.sh
> +  mv_vrfy BGDAWP.GrbF${post_fhr}.${fmn} ${postprd_dir}/${NET}.t${cyc}z.bgdawpf${fhr}${fmn}.${tmmark}.grib2
Also, to avoid repeating the move commands (including the hard-coded file names) in two places, can rewrite this if-statement this way:
```
dot_post_mn_or_null=""
if [ "${post_mn}" = "00" ]; then
  dot_post_mn_or_null=".${post_mn}"
fi
mv_vrfy BGDAWP.GrbF${post_fhr}${dot_post_mn_or_null} ${postprd_dir}/${NET}.t${cyc}z.bgdawpf${fhr}${fmn}.${tmmark}.grib2
mv_vrfy BGRD3D.GrbF${post_fhr}${dot_post_mn_or_null} ${postprd_dir}/${NET}.t${cyc}z.bgrd3df${fhr}${fmn}.${tmmark}.grib2
```

2021-02-26 21:28 UTC, Jeff-Duda commented on ush/templates/FV3LAM_wflow.xml
> +
That's a good point, Gerard. I have never run FV3 with dt_atmos > 59, so I can't say I'll know how the output file name will look. I would imagine it would get converted into minutes, so perhaps that will have to be examined and tested first.

2021-02-26 21:31 UTC, Jeff-Duda commented on scripts/exregional_run_fcst.sh
> +  delta_fmin="${DT_SUBHOURLY_POST_MNTS}" \
Changed here as well as in create_model_configure_file.sh

2021-02-26 21:34 UTC, Jeff-Duda commented on scripts/exregional_run_post.sh
> +len_fmin=${#fmn}
I kept the warning part in there in case ${fmn} is misspecified coming from JREGIONAL_RUN_POST. Otherwise, ${post_fmn} was removed.

2021-02-26 21:34 UTC, Jeff-Duda commented on scripts/exregional_run_post.sh
> +post_min=${post_time:10:2}
Made suggested change.

2021-02-26 21:42 UTC, Jeff-Duda commented on scripts/exregional_run_post.sh
> +  mv_vrfy BGDAWP.GrbF${post_fhr}.${fmn} ${postprd_dir}/${NET}.t${cyc}z.bgdawpf${fhr}${fmn}.${tmmark}.grib2
The logical operator is inverted from what it should be, but otherwise I implemented this change as suggested.

2021-02-26 21:52 UTC, Jeff-Duda commented on ush/setup.sh
> +  SUB_HOURLY_POST="FALSE"
Done as suggested.

2021-02-26 21:53 UTC, Jeff-Duda commented on ush/create_model_configure_file.sh
> +delta_fmin \
Done as indicated from a previous comment.

2021-02-26 21:57 UTC, Jeff-Duda commented on ush/create_model_configure_file.sh
> +  if [ "${sub_hourly_post}" = "TRUE" ]; then
Done.

2021-02-26 21:58 UTC, Jeff-Duda commented on jobs/JREGIONAL_RUN_POST
> +if [[ "${fmn}" ]] && [[ ! "${DT_ATMOS}" ]]; then
Done as suggested.

2021-02-26 22:02 UTC, Jeff-Duda commented on ush/create_model_configure_file.sh
> +   ((nsout = delta_fmin*60 / dt_atmos))
This calculation is the integer value ('/'), not the remainder ('%'). So no, $nsout will not always be 0.

2021-02-26 22:59 UTC, Jeff-Duda commented on ush/setup.sh
> +  rem = ${val}
Replaced line as suggested.

2021-03-01 17:10 UTC, gsketefian commented
@Jeff-Duda Thanks for addressing the comments.  Can you also push your latest to your fork so we can see the changes?  I see your comments stating the changes you've made, but I don't see the actual changes in the files.  I assume it's because you haven't yet pushed your latest.  Thx.

2021-03-01 20:34 UTC, Jeff-Duda commented on ush/templates/FV3LAM_wflow.xml
> +
I ran a test with dt_atmos > 59 and it turns out the FV3 output is properly formatted using fFFF:mm:SS, so it correctly converts seconds-past-59 to minutes & seconds. So i modified the template file and generation script accordingly.

During this investigation I discovered I had modified the workflow template incorrectly...all post tasks would have their dependency met as soon as the very first FV3 file was available, which is undesirable. Fixing this required me to separate the one metatask set into two separate tasks; the new one runs UPP only on that very first FV3 output file ("f00000"). However, it is essentially impossible to remove that same time from the metatask setup without further separating the tasks, which seems unnecessarily cumbersome. So the result is that there will be two f00000 post tasks, and one of them will never run (since the exact "dynf000:00:00.nc" file will never exist).

2021-03-01 21:55 UTC, gsketefian commented on ush/setup.sh
> +    ((val = (DT_SUBHOURLY_POST_MNTS*60) % DT_ATMOS))
Change line 1020-1021 to the following, otherwise the message will fail (because rem further below would not be defined:
```
    rem=$(( (DELTA_MIN*60) % DT_ATMOS ))
    if [ "$rem" -ne "0" ]; then

```

2021-03-01 22:16 UTC, gsketefian commented on ush/create_model_configure_file.sh
> +  # nfhout is the forecast hour output interval (provided forecast length is at most 60 hours)
Can you work the following in your comments here?  Thanks.

If performing sub-hourly post-processing, specify the output frequency in units of number of forecast model time steps (i.e. specify nsout).  Note that nsout is guaranteed to be an integer because a check has been placed in the experiment generation scripts to ensure that in this case, the remainder of dt_subhourly_post_mnts*60 divided by dt_atmos is zero.  If not performing sub-hourly post-processing, specify the output frequency in units of hours (i.e. specify nfhout).

2021-03-03 17:29 UTC, Jeff-Duda commented on ush/setup.sh
> +    ((val = (DT_SUBHOURLY_POST_MNTS*60) % DT_ATMOS))
Done.

2021-03-03 17:37 UTC, gsketefian commented on ush/setup.sh
> +    ((val = (DT_SUBHOURLY_POST_MNTS*60) % DT_ATMOS))
@Jeff-Duda Hey Jeff, it is easier for the reviewers if you push your changes and let the reviewers resolve the conversation once they can see that it's actually been pushed.  Often people make the change on their clone but forget to push.  For example, in this case, I don't yet see any changes.  Thx.

2021-03-03 17:48 UTC, Jeff-Duda commented on ush/setup.sh
> +    ((val = (DT_SUBHOURLY_POST_MNTS*60) % DT_ATMOS))
I don't know what to say then...that is exactly the change I made, committed, and pushed...

`[Jeffrey.Duda@hfe09 ush]$ git diff b5d8c4701a5b3622f9b9a0577ad278536f1fbe6d f49aee6e66223df34453753fbedb070eb8ecc235
diff --git a/ush/create_model_configure_file.sh b/ush/create_model_configure_file.sh
index 463e48f4..11c3a2d3 100644
--- a/ush/create_model_configure_file.sh
+++ b/ush/create_model_configure_file.sh
@@ -173,10 +173,9 @@ run directory (run_dir):

   fi

-  # IF using sub-hourly FV3/UPP output, then the FV3 output interval needs to be specified in
-  # units of multiples of model time steps (nsout). nsout is guaranteed to be an integer because
-  # consistency between ${DT_SUBHOURLY_POST_MNTS} and ${DT_ATMOS} was enforced at the time of script generation.
-  # ELSE only nfhout is used and set to 1-hour output.
+  # nfhout is the forecast hour output interval (provided forecast length is at most 60 hours)
+  # nsout is the output interval in multiples of dt_atmos; it is useful for controlling sub-hourly FV3 output
+  # in the below formulation, it is explicitly designed for minute-specific (rather than second-specifc) output
   if [ "${sub_hourly_post}" = "TRUE" ]; then
    nsout=$(( dt_subhourly_post_mnts*60 / dt_atmos ))
    nfhout=0
diff --git a/ush/setup.sh b/ush/setup.sh
index 1858b184..245479b3 100755
--- a/ush/setup.sh
+++ b/ush/setup.sh
@@ -1017,8 +1017,8 @@ configuration file (EXPT_CONFIG_FP) and rerun:
   EXPT_CONFIG_FP = \"${EXPT_CONFIG_FP}\""
 else
   if [ "${SUB_HOURLY_POST}" = "TRUE" ]; then
-    ((rem = (DT_SUBHOURLY_POST_MNTS*60) % DT_ATMOS))
-    if [ ${rem} -ne 0 ]; then
+    ((val = (DT_SUBHOURLY_POST_MNTS*60) % DT_ATMOS))
+    if [ ${val} -ne 0 ]; then
       print_err_msg_exit "\
 When performing sub-hourly post (i.e. SUB_HOURLY_POST set to \"TRUE\"), the time
 interval specified by DT_SUBHOURLY_POST_MNTS (after converting to seconds) must be evenly divisible`

2021-03-03 18:52 UTC, gsketefian commented
@Jeff-Duda Can you point me to experiment directories where you've run with the subhourly post (and preferably another one without) so I can better understand the output file names, etc in the two cases?  Having a task that doesn't ever run will throw off the WE2E test system (the part where it reports whether the workflow for each test completed successfully or not), so I'd like to see what it will take to fix that.  Thx.

2021-03-03 19:04 UTC, Jeff-Duda commented
> 
> 
> @Jeff-Duda Can you point me to experiment directories where you've run with the subhourly post (and preferably another one without) so I can better understand the output file names, etc in the two cases? Having a task that doesn't ever run will throw off the WE2E test system (the part where it reports whether the workflow for each test completed successfully or not), so I'd like to see what it will take to fix that. Thx.

You can check out this space on Hera: /scratch1/BMC/wrfruc/jdduda/FV3_workflows/derecho_2020

2021-03-03 19:16 UTC, gsketefian commented
@Jeff-Duda Thanks, that helps to see what's going on.  Do you have one when SUB_HOURLY_POST is set to FALSE?  I'd like to see how the file and task names are going to change from what they are now for that case.

2021-03-03 19:17 UTC, Jeff-Duda commented
> 
> 
> @Jeff-Duda Thanks, that helps to see what's going on. Do you have one when SUB_HOURLY_POST is set to FALSE? I'd like to see how the file and task names are going to change from what they are now for that case.

Not at this time, but I can create one in /scratch1/BMC/wrfruc/jdduda/FV3_workflows/test_hourly

2021-03-03 19:20 UTC, gsketefian commented
That would be great.  I would test your PR myself but am way over hours for this FV3LAM support project.

2021-03-03 19:24 UTC, Jeff-Duda commented
Okay...a workflow is running at that location. Check back periodically throughout the day to see the progress.

2021-03-03 19:33 UTC, gsketefian commented
If/when you try without sub-hourly post, just one cycle will be sufficient.

Btw, in the workflow's community mode (which is what you're using, I think), there is a way to skip the pre-processing tasks if you've already generated the grid, orography, and surface climatology files for the grid.  Below is from an email I sent to another user who asked about this:

```
Ok, to skip the make_grid, make_orog, and make_sfc_climo tasks, first create a directory in which to place pregenerated 
copies of these files.  For example, for the 25km CONUS grid, I've put the files in this directory (on Hera):

/scratch2/BMC/det/FV3LAM_pregen/RRFS_CONUS_25km

Then you'll have to add the following lines to your config.sh file (where I'm using the directory above for GRID_DIR, 
OROG_DIR, and SFC_CLIMO_DIR):

#
# Set RUN_TASK_MAKE_GRID to "FALSE" to skip the MAKE_GRID_TN task.  In 
# this case, the directory containing the pregenerated grid files (GRID_DIR)
# must be specified.
#
RUN_TASK_MAKE_GRID="FALSE"
GRID_DIR="/scratch2/BMC/det/FV3LAM_pregen/RRFS_CONUS_25km"
#
# Set RUN_TASK_MAKE_OROG to "FALSE" to skip the MAKE_OROG_TN task.  In 
# this case, the directory containing the pregenerated orography files 
# (OROG_DIR) must be specified.
#
RUN_TASK_MAKE_OROG="FALSE"
OROG_DIR="/scratch2/BMC/det/FV3LAM_pregen/RRFS_CONUS_25km"
#
# Set RUN_TASK_MAKE_SFC_CLIMO to "FALSE" to skip the MAKE_SFC_CLIMO_TN 
# task.  In this case, the directory containing the pregenerated surface
# climatology files (SFC_CLIMO_DIR) must be specified.
#
RUN_TASK_MAKE_SFC_CLIMO="FALSE"
SFC_CLIMO_DIR="/scratch2/BMC/det/FV3LAM_pregen/RRFS_CONUS_25km"

An example of an experiment that does this can be found here on Hera:

/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/PR_feature_nco_fix_links/expt_dirs/links02/pregen_grid_orog_sfc_climo

Please let me know if you run into any difficulties.  Thanks,
Gerard
```

2021-03-08 18:11 UTC, gsketefian requested changes

2021-03-08 18:11 UTC, gsketefian commented on ush/setup.sh
> +    ((rem = (DT_SUBHOURLY_POST_MNTS*60) % DT_ATMOS))
For consistency with the rest of the scripts, let's do math this way:
`rem=$(( (DT_SUBHOURLY_POST_MNTS*60) % DT_ATMOS ))
`
Thanks.

2021-03-08 18:11 UTC, gsketefian commented on ush/templates/FV3LAM_wflow.xml
> +
Haven't yet gotten a chance to look at this issue in detail due to urgent work on the release of the SRW app and it being somewhat complicated.

2021-03-08 18:11 UTC, gsketefian commented on ush/templates/FV3LAM_wflow.xml
> +              <and>
Are the dynf and phyf file names always going to include the minute now, i.e. even when SUB_HOURLY_POST is set to FALSE?  If so, then are lines 443-446 needed?

2021-03-08 18:11 UTC, gsketefian commented on ush/templates/FV3LAM_wflow.xml
> +              <and>
After looking at the output netcdf file names with and without subhourly post that you ran, it seems like the minutes and seconds will not be appended to the file names in the "without" case.  So to simplify the final xml that is generated, the `<or>` can be removed and either the first `<and>` (for subhourly enabled) or the second `<and>` (for subhourly disabled) can be kept, i.e. I'm thinking of replacing lines 438-447 with something like this:
```
            <and>
{% if sub_hourly_post %}
              <datadep age="05:00"><cyclestr>&CYCLE_BASEDIR;/@Y@m@d@H{{ slash_ensmem_subdir}}/dynf#fhr#:#fmin#:00.nc</cyclestr></datadep>
              <datadep age="05:00"><cyclestr>&CYCLE_BASEDIR;/@Y@m@d@H{{ slash_ensmem_subdir}}/phyf#fhr#:#fmin#:00.nc</cyclestr></datadep>
{% else %}
              <datadep age="05:00"><cyclestr>&CYCLE_BASEDIR;/@Y@m@d@H{{ slash_ensmem_subdir}}/dynf#fhr#.nc</cyclestr></datadep>
              <datadep age="05:00"><cyclestr>&CYCLE_BASEDIR;/@Y@m@d@H{{ slash_ensmem_subdir}}/phyf#fhr#.nc</cyclestr></datadep>
{% endif %}
            </and>

```

2021-03-08 18:11 UTC, gsketefian commented on ush/templates/FV3LAM_wflow.xml
The problem with having a task that never launches (run_post_f00000) is that it will throw off the way the workflow end-to-end testing system because that system checks that all workflow tasks have completed successfully before declaring the workflow status a "SUCCESS".  But I think there is a way to fix this for the subhourly-enabled case by splitting the loop over hours into tasks for the first hour and a loop over the remaining hours, as follows:
```
{% if sub_hourly_post %}
  ==> Move lines 458-487 (in the new file) that define the run_post_f00000 task to here.  This portion 
      does not need fhr or fmin because it will just use {{ first_fcst_file_tstr }}.
  ==> For the first hour (fhr=0), loop over the minutes, not starting with the 0th but instead with delta_min:
      <var name="fmin">{% for min in range(delta_min, 60,delta_min) %}{{ " %02d" % min  }}{% endfor %}</var>
      <metatask>
      ...
      </metatask>
{% endif %}
==> Now make the starting hour of the main loop over fhr start on the second hour (fhr=1) if subhourly is 
    enabled; otherwise start on the first hour (fhr=0):
{% if sub_hourly_post %}
    <var name="fhr">{% for h in range(1, fcst_len_hrs+1) %}{{ " %03d" % h  }}{% endfor %}</var>
{% else %}
    <var name="fhr">{% for h in range(0, fcst_len_hrs+1) %}{{ " %03d" % h  }}{% endfor %}</var>
{% endif %}
==> Put lines 410-455 (in the new file) here to do the usual (including looping over all minutes, starting 
    with 0).
```
You can combine the two if-statements above into one if you like.  I didn't because it was clearer to me this way.

2021-03-08 18:34 UTC, gsketefian commented
@Jeff-Duda Sorry for the late reply to your changes.  I had actually made the most recent sent of comments mid last-week but apparently forgot to press the right button for you to see them.

If you'd like to have an in-person meeting to work through these, I'm happy to do it.

2021-03-08 20:17 UTC, Jeff-Duda commented on ush/setup.sh
> +    ((rem = (DT_SUBHOURLY_POST_MNTS*60) % DT_ATMOS))
That is how the code currently looks.

2021-03-08 20:26 UTC, Jeff-Duda commented on ush/templates/FV3LAM_wflow.xml
> +              <and>
addressed

2021-03-08 20:26 UTC, Jeff-Duda commented on ush/templates/FV3LAM_wflow.xml
addressed

2021-03-10 00:18 UTC, gsketefian commented
@Jeff-Duda This looks pretty good.  I'm trying testing it now and may add one or two WE2E tests so that future PRs don't break the subhourly post capability.

In the meantime, could you merge the latest from the develop branch into your branch and push it to your fork?  I just merged develop into my copy of your branch and there were no conflicts, so it should be straightforward.  Thanks.

2021-03-10 17:12 UTC, Jeff-Duda commented
Not sure I did the merging correctly, but have a look and see if this is ready.

2021-03-12 19:59 UTC, gsketefian commented
@Jeff-Duda I ran tests and had to fix a couple of bugs in the PR.  The biggest change was the rearrangement of the XML.  I created a PR (#[1](https://github.com/Jeff-Duda/regional_workflow/pull/1)) from my fork into yours so you can pull my changes into your fork.  I'm waiting for the 3 WE2E tests I launched to finish; I don't think there will be a problem, but I'll let you know for sure when they're done.  Feel free to retest if you like.

The only other thing left is to make sure that the PR message above is up-to-date because I'm going to use it as the commit message, i.e. I'm going to cut-and-paste when I do the "squash-and-merge", so the PR message is what will show up when you do a "git log".

2021-03-12 22:48 UTC, gsketefian commented
@Jeff-Duda The three WE2E tests I ran were all successful.  Please let me know if/when your PR message is updated and we can merge.

2021-03-12 23:05 UTC, Jeff-Duda commented
I did perform a merge with your changes a few hours ago. What more do I need to do?

2021-03-13 00:16 UTC, gsketefian commented
@Jeff-Duda I don't mean that merge, I mean the final merge for your PR where we (I, really) take all of your commits in this PR, squash them into one, and merge that single commit into the authoritative branch.  This is done via the "Squash and merge" button below.  I have to do that.  That process requires a commit message that will show up when someone does a "git log" on the develop branch, and I'm going to use your PR message above as that message.  So I just want to make sure that it is up-to-date.  For example, I see that it refers to the DELTA_MIN variable, but we changed that to DT_SUBHOURLY_POST_MNTS.  Just update those details and let me know when it's ready and I'll merge it and close this PR.  Thanks.

2021-03-13 02:50 UTC, Jeff-Duda commented
Update them where?

2021-03-13 03:04 UTC, JeffBeck-NOAA commented
@Jeff-Duda, at the top of this conversation, you'll see the original location where you described the PR (Description of Changes, Tests Conducted, Issue (Optional)).  There's an option to edit that message.

2021-03-13 03:09 UTC, gsketefian commented
@Jeff-Duda At the top of this PR page, there is a box containing the message you wrote a while ago that describes the changes this PR makes.  It has sections like "Description of Changes", "Test Conducted", and "Issue (optional)" that you filled out.  Once you find that message, you'll see a button with three dots (...) in the upper-right corner of the box containing the message.  Press that, then press "Edit", and edit your message so it's up-to-date.  Then press the green "Update Comment" button that will show up at the bottom of the message box.  You can repeat this process as many times as you like until you're satisfied that the PR message adequately and correctly described the changes that this PR makes to the repo.  Once you're done, let me know and I'll merge your PR into the authoritative "develop" branch of this repo (I'll use your PR message as the message for the single commit that all your changes will be grouped under).

2021-03-13 17:44 UTC, Jeff-Duda commented
Okay, I think I am comfortable with the edits to my original message now. Youc an move forward.

2021-03-15 22:03 UTC, merged

2021-03-15 22:11 UTC, gsketefian commented
@Jeff-Duda I just merged this PR.  In the PR message, I added a few lines about my bug fixes and noted that this PR changes the way the UPP grib2 output files are named even in the case of SUB_HOURLY_POST set to "FALSE", in which case "00" minutes is added to the names of the files.

I will submit another PR soon that will introduce a couple of WE2E tests involving subhourly post-processing.