Adding gsl gwd oro data files
NOAA-EMC/regional_workflow pull request #448
Opened 2021-02-26 22:47 UTC by mdtoy

## DESCRIPTION OF CHANGES: 
One or more paragraphs describing the problem, solution, and required changes.

## TESTS CONDUCTED: 
Explicitly state what tests were run on these changes, or if any are still pending (for README or other text-only changes, just put "None required". Make note of the compilers used, the platform/machine, and other relevant details as necessary. For more complicated changes, or those resulting in scientific changes, please be explicit!

## CONTRIBUTORS (optional): 
If others have contributed to this work aside from the PR author, list them here

2021-03-04 19:42 UTC, gsketefian commented on scripts/exregional_make_orog.sh
>  #
Could you update the comments above this line?  I forgot to point this out earlier.  Thx.

2021-03-04 19:53 UTC, gsketefian commented
@mdtoy This looks good.  Just a minor request:  In the PR message, can you mention for config_defaults.sh that you removed the workflow variable GWD_HRRRsuite_BASEDIR since it's no longer needed?  Once you do that and update the comment in exregional_make_orog.sh, it's just a matter of waiting for the UFS_UTILS PR #[273](https://github.com/NOAA-EMC/UFS_UTILS/pull/273) to get merged (looks like it hasn't been merged yet).

2021-03-08 17:10 UTC, mdtoy commented on scripts/exregional_make_orog.sh
>  #
Done

2021-04-27 15:44 UTC, mkavulich requested changes
This PR looks good aside from my one comment.

2021-04-27 15:44 UTC, mkavulich commented on scripts/exregional_make_orog.sh
> +  if [ "${MACHINE}" = "WCOSS_CRAY" ]; then
The `--relative` flag does not work on MacOS either, and probably many Linux distros if my glance at the various man pages out there is representative. Can we just omit the flag completely rather than introducing this logic?

2021-04-27 15:45 UTC, mkavulich commented on scripts/exregional_make_orog.sh
> +  if [ "${MACHINE}" = "WCOSS_CRAY" ]; then
Sorry apparently I can't figure out GitHub's line-highlighting capability; this comment refers to the following several lines

2021-04-27 18:05 UTC, JeffBeck-NOAA commented on scripts/exregional_make_orog.sh
> +  tmp_dir="${OROG_DIR}/temp_orog_data"
@mdtoy, since "temp_orog_data" is the final directory to store the GSL GWD files, can we change the name to something like "gsl_orog_data"?

2021-04-27 18:37 UTC, mdtoy commented on scripts/exregional_make_orog.sh
> +  tmp_dir="${OROG_DIR}/temp_orog_data"
The GSL oro_data files are created in tmp_dir, but then a few lines down (on line 370) they are moved to their permanent location at ${OROG_DIR}.

370   mv_vrfy "${CRES}${DOT_OR_USCORE}oro_data_ss.tile${TILE_RGNL}.halo${NH0}.nc" \
371           "${CRES}${DOT_OR_USCORE}oro_data_ls.tile${TILE_RGNL}.halo${NH0}.nc" \
372           "${OROG_DIR}"

2021-04-27 18:57 UTC, JeffBeck-NOAA commented on scripts/exregional_make_orog.sh
> +  tmp_dir="${OROG_DIR}/temp_orog_data"
Sorry, @mdtoy!  I see it now.  Resolving this conversation.

2021-04-27 19:12 UTC, JeffBeck-NOAA approved these changes
Successfully tested on Hera with the FV3_HRRR SDF.  Approving this PR.  Hopefully it can be merged shortly after Mike's comment is addressed.

2021-05-03 17:21 UTC, JeffBeck-NOAA commented
@mdtoy, any update on this PR/@mkavulich's comment?

2021-05-05 00:44 UTC, mkavulich commented on scripts/exregional_make_orog.sh
> +  if [ "${MACHINE}" = "WCOSS_CRAY" ]; then
@mdtoy Any updates?

2021-05-05 20:33 UTC, mkavulich approved these changes

2021-05-05 20:33 UTC, mkavulich commented
Offline discussion resolved my issues, this PR can be merged.

2021-05-05 20:44 UTC, merged