Make the METplus tasks work on WCOSS
NOAA-EMC/regional_workflow pull request #483
Opened 2021-04-29 14:56 UTC by chan-hoo

## DESCRIPTION OF CHANGES: 
- The modulefiles required for the metplus tasks are added to 'modulefiles/tasks/wcoss_cray(and wcoss_dell_p3).
- The workflow template is modified for the metplus tasks.
- The MRMS REFC verification does not work correctly on the Dell due to a problem with the MET installation (v9.1.3).
- The version of MET is changed to the latest on Hera (v9.0.2 to v9.1).

## TESTS CONDUCTED: 
config.sh files used for:
- WCOSS Dell: https://github.com/chan-hoo/regional_workflow_config/blob/main/wcoss_dell/config_community_conus25_metplus_staged.sh

![APCP_03_CSI_WCOSS_Dell](https://user-images.githubusercontent.com/60152248/116571616-3f66bf80-a8d9-11eb-959d-7b85e0789a02.png)

- WCOSS Cray: https://github.com/chan-hoo/regional_workflow_config/blob/main/wcoss_cray/config_community_conus25_metplus_staged.sh

![APCP_03_CSI_WCOSS_Cray](https://user-images.githubusercontent.com/60152248/116571664-47befa80-a8d9-11eb-9acb-281874e0f6ed.png)

- Hera: https://github.com/chan-hoo/regional_workflow_config/blob/main/hera/config_community_conus25_metplus_staged.sh

![APCP_03_CSI_Hera](https://user-images.githubusercontent.com/60152248/116571698-4db4db80-a8d9-11eb-8f01-9a2414b1e690.png)

## ISSUE:
Fixes issue mentioned in #482  

## CONTRIBUTORS: 
@BenjaminBlake-NOAA, @PerryShafran-NOAA, @LoganDawson-NOAA

2021-04-29 15:47 UTC, JeffBeck-NOAA requested changes

2021-04-29 15:47 UTC, JeffBeck-NOAA commented on ush/templates/FV3LAM_wflow.xml
>      <nodes>{{ nnodes_get_obs_ccpa }}:ppn={{ ppn_get_obs_ccpa }}</nodes>
For all Jinja "if" statements (all three parts, "if", "else", "endif"), can you add a "-" after the % to avoid adding additional blank lines in the final XML file?  You can see examples of how that's done in [this](https://github.com/NOAA-EMC/regional_workflow/pull/479/files#diff-8039940ddde4e92265c83a9ee50165c7047ea7dd084d68d3db45a6c20cabb85a) FV3LAM_wflow.xml example for another PR.  Thanks!

2021-04-29 17:50 UTC, chan-hoo commented on ush/templates/FV3LAM_wflow.xml
>      <nodes>{{ nnodes_get_obs_ccpa }}:ppn={{ ppn_get_obs_ccpa }}</nodes>
@JeffBeck-NOAA, completed!

2021-04-29 17:58 UTC, BenjaminBlake-NOAA commented
@chan-hoo I'll retrieve the latest updates and re-run the metplus jobs on the Dell to make sure the changes related to the MRMS REFC verification work properly

2021-04-29 18:07 UTC, JeffBeck-NOAA commented on ush/templates/FV3LAM_wflow.xml
>      <nodes>{{ nnodes_get_obs_ccpa }}:ppn={{ ppn_get_obs_ccpa }}</nodes>
Thank you!

2021-04-29 18:08 UTC, JeffBeck-NOAA approved these changes

2021-04-30 18:13 UTC, chan-hoo commented
@BenjaminBlake-NOAA, all the issues on the MRMS REFC verification on the Dell have been fixed.

2021-05-03 14:56 UTC, BenjaminBlake-NOAA approved these changes
@chan-hoo I tested the latest version on the Dell and everything appears to have worked, so I'm good to approve these changes!  My output is here on WCOSS if you want to take a quick look:
/gpfs/dell2/emc/modeling/noscrub/Benjamin.Blake/expt_dirs/test_metplus

2021-05-03 15:05 UTC, merged