WE2E test for MET verification.
NOAA-EMC/regional_workflow pull request #537
Opened 2021-07-03 17:41 UTC by siwei-noaa

## DESCRIPTION OF CHANGES: 
This is a WE2E test for MET verification capability in the regional workflow.
There are 2 changes in this PR: 
(1) Add one file: tests/baseline_configs/config.MET_validation.sh
(2) Add a line in the tests/baselines_list.txt

## TESTS CONDUCTED: 
A test run was conducted and has been finished successfully.

## DEPENDENCIES:
To have MET verification run successfully, the observational data (e.g., CCPA, MRMS, NDAS) must be available. 

## DOCUMENTATION:
N/A

2021-07-04 02:12 UTC, JeffBeck-NOAA requested changes
Thanks @siwei-noaa!  One minor comment: can you add the header to the config file you see in Gerard's PR [here](https://github.com/NOAA-EMC/regional_workflow/pull/531/files#diff-5b58f28c5a554b7fa085ee8d5ef23d3d0c4204a9ff200f7aaa129717a0c7f382)?  Just provide a description for the WE2E you're contributing.  Thanks!

2021-07-04 15:25 UTC, siwei-noaa commented
Hi Jeff, thank you for sharing the template. I just added the header. Please let me know if you need additional changes.

2021-07-04 16:54 UTC, JeffBeck-NOAA commented
Thanks, @siwei-noaa!  Looks good!  Approving now.

2021-07-04 16:54 UTC, JeffBeck-NOAA approved these changes

2021-07-06 20:12 UTC, gsketefian commented on tests/baseline_configs/config.MET_validation.sh
> +# completes successfully with MET verification.
Is it "verification" or "validation"?  Says validation here, but the test/file name is "MET_validation".

2021-07-06 20:26 UTC, siwei-noaa commented on tests/baseline_configs/config.MET_validation.sh
> +# completes successfully with MET verification.
Hi Gerard, thanks for asking. Sorry for my English. I interchanged them here. Should we use verification instead of validation?

2021-07-06 23:04 UTC, gsketefian commented on tests/baseline_configs/config.MET_validation.sh
> +# completes successfully with MET verification.
It's confusing!  Well in other scripts in the workflow they are called "verification" tasks, so I guess it should be "verification".

2021-07-06 23:05 UTC, gsketefian commented on tests/baseline_configs/config.MET_validation.sh
> +MODEL="FV3_GFS_v15p2_CONUS_25km"
Do these paths only work on Hera?

2021-07-07 17:37 UTC, jwolff-ncar commented on tests/baseline_configs/config.MET_validation.sh
> +MODEL="FV3_GFS_v15p2_CONUS_25km"
We have not yet ported the verification tasks to any other machines so these are currently specific to Hera.

2021-07-07 17:37 UTC, jwolff-ncar commented on tests/baselines_list.txt
> +MET_validation
Is this what will be changed to MET_verification?

2021-07-13 16:49 UTC, gsketefian commented on tests/baselines_list.txt
> +MET_validation
@jwolff-ncar Yes, @siwei-noaa did this.

2021-07-13 16:53 UTC, JeffBeck-NOAA approved these changes

2021-07-13 16:53 UTC, merged

2021-07-13 17:06 UTC, gsketefian commented on tests/baseline_configs/config.MET_verification.sh
> +MODEL="FV3_GFS_v15p2_CONUS_25km"
In order to allow this test to fail gracefully (and informatively) on machines other than Hera, let's use the same approach as is used for other WE2E tests that only run on some machines.  Namely, in run_experiments.sh, add something like this:
```
#
#-----------------------------------------------------------------------
#
# Set MET and MET+ paths, if necessary.
#
#-----------------------------------------------------------------------
#
  if [ ${RUN_TASK_VX_GRIDSTAT} = "TRUE" ] || \
     [ ${RUN_TASK_VX_POINTSTAT} = "TRUE" ]; then  <-- I am not sure if these are the correct tests; please fix as necessary.

    if [ "$MACHINE" = "HERA" ]; then
      
met_install_dir="/contrib/met/10.0.0"
      metplus_path="/contrib/METplus/METplus-4.0.0"
    else
      print_err_msg_exit "\
The MET and MET+ paths have not been specified for this machine (MACHINE):
  MACHINE= \"${MACHINE}\""
    fi

    str=${str}"
#
# MET and MET+ paths.
#
METPLUS_PATH=\"${metplus_path}\"
MET_INSTALL_DIR=\"${met_install_dir}\""

  fi
```
This can go right after a similar stanza for USE_USER_STAGED_EXTRN_FILES around line 700 of run_experiments.sh.  Feel free to modify this code as necessary (I just made a best guess of what the code should be, and I haven't tested it).

2021-07-13 17:20 UTC, JeffBeck-NOAA commented on tests/baseline_configs/config.MET_verification.sh
> +MODEL="FV3_GFS_v15p2_CONUS_25km"
Sorry @gsketefian, @siwei-noaa, I merged this PR after Siwei's latest change, since I thought it had been completely reviewed aside from that minor change.  @siwei-noaa, do you mind adding a new PR with @gsketefian's recommended modifications?  My apologies.

2021-07-13 17:25 UTC, gsketefian commented on tests/baseline_configs/config.MET_verification.sh
> +MODEL="FV3_GFS_v15p2_CONUS_25km"
@JeffBeck-NOAA No problem.  I was late to review it.  Just can't keep up with all the work.  We can use this approach (of making new PRs) in the future too, I don't mind.  Just have to reference the original PR in the new one.

2021-07-13 17:30 UTC, siwei-noaa commented on tests/baseline_configs/config.MET_verification.sh
> +MODEL="FV3_GFS_v15p2_CONUS_25km"
Thank you for the information. I forgot to solve the "Hera Only" issue. I will add a new PR.
By the way, `met_install_dir` and `metplus_path` should be assigned in the config.sh or need to be included here? Will they overwrite the values from config.sh?

2021-07-13 18:49 UTC, JeffBeck-NOAA commented on tests/baseline_configs/config.MET_verification.sh
> +MODEL="FV3_GFS_v15p2_CONUS_25km"
@siwei-noaa, my guess is if they're defined in the run_experiments script (based on what @gsketefian has proposed), they should not be included in the config.MET_verification.sh script.  I'm not sure which of those two takes precedence.  @gsketefian?

2021-07-14 01:03 UTC, gsketefian commented on tests/baseline_configs/config.MET_verification.sh
> +MODEL="FV3_GFS_v15p2_CONUS_25km"
@siwei-noaa `met_install_dir` and `metplus_path` are just local variables in `run_experiment.sh`.  You don't need to (and shouldn't) assign them in `config.sh`.  I just use them to store the values we want for MET_INSTALL_DIR and METPLUS_PATH, respectively, until those values are recorded in the mult-iline string `str` later below.  `str` that contains everything that will be written out to the final configuration file (`config.sh`) for the current WE2E test being considered (in the loop over all user-specified tests).  Oh, I forgot to mention that you should remove the lines for MET_INSTALL_DIR and METPLUS_PATH from `config.MET_verification.sh`.  Gotta run now but am happy to talk about it more tomorrow.