Add inline post option to the SRW App
NOAA-EMC/regional_workflow pull request #538
Opened 2021-07-06 11:26 UTC by chan-hoo

## DESCRIPTION OF CHANGES: 
- Add the parameter 'write_dopost' for inline post to model_configure.
- Turn off the 'run_post' task when 'write_dopost'='.true.'
- Add post-processing for inline post to the 'run_fcst' script.
- Modify the dependency for verification in the workflow template.
- Add a new WE2E test for inline post.

## TESTS CONDUCTED: 
- GST + verification on Hera and WCOSS Dell
- New WE2E test for inline post

## DEPENDENCIES:
- https://github.com/ufs-community/ufs-srweather-app/pull/150

## ISSUE: 
- Fixes issue mentioned in #511

2021-07-06 19:41 UTC, JeffBeck-NOAA requested changes

2021-07-06 19:41 UTC, JeffBeck-NOAA commented on ush/config_defaults.sh
>  #
Could this variable be called "DO_INLINE_POST" instead?  I assume WRITE_DOPOST refers to running post within the write component, but it might be confusing to those not familiar with how that works.

2021-07-06 19:41 UTC, JeffBeck-NOAA commented on ush/templates/FV3LAM_wflow.xml
>    </task>
In addition to these if statements for dependencies, can you wrap the RUN_POST task in an if statement to not include it if inline post is used?

2021-07-06 19:46 UTC, JeffBeck-NOAA commented on ush/config_defaults.sh
>  #
Actually, it looks like the new variable in the model_configure file is "write_dopost", so maybe it makes sense to define it that way everywhere.  You've described what it means here, so it's probably fine.

2021-07-06 19:53 UTC, JeffBeck-NOAA requested changes
It doesn't look like WRITE_DOPOST automatically sets RUN_TASK_RUN_POST=FALSE anywhere.  Can you make this change in setup.sh?

2021-07-06 20:01 UTC, chan-hoo commented
@JeffBeck-NOAA, You can find it on Line 2139 in setup.sh

2021-07-06 20:36 UTC, JeffBeck-NOAA commented
> @JeffBeck-NOAA, You can find it on Line 2139 in setup.sh

Thanks!  Just missed it.

2021-07-06 20:36 UTC, JeffBeck-NOAA approved these changes

2021-07-06 20:43 UTC, JeffBeck-NOAA commented
@chan-hoo, can you add a header to the WE2E test you've included in this PR?  You can check out [this](https://github.com/NOAA-EMC/regional_workflow/pull/531) PR to see how we're handling that now.  Thanks!

2021-07-07 15:47 UTC, JeffBeck-NOAA approved these changes

2021-07-07 15:51 UTC, merged

2021-07-08 07:21 UTC, gsketefian commented
@chan-hoo I was just merging this into one of my feature branches, and I started wondering if setting WRITE_DOPOST="TRUE" works with SUB_HOURLY_POST="TRUE"?  If not, we should at least add a check, e.g. quit out of the experiment generation script if both of these are TRUE, and make an issue to fix this later on.  Thanks.

2021-07-08 07:31 UTC, gsketefian commented on scripts/exregional_run_fcst.sh
> +    COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/$cyc${SLASH_ENSMEM_SUBDIR}"
I think `cyc` is being used here before being set (below) since I don't see it set in JREGIONAL_RUN_FCST or FV3LAM_wflow.xml.  Maybe this was missed because the WE2E test is in community mode.

2021-07-08 08:05 UTC, gsketefian commented on scripts/exregional_run_fcst.sh
> +    echo $fhr
Remove echo?

2021-07-08 10:22 UTC, chan-hoo commented on scripts/exregional_run_fcst.sh
> +    COMOUT="${COMOUT_BASEDIR}/$RUN.$PDY/$cyc${SLASH_ENSMEM_SUBDIR}"
@gsketefian, I'll fix this in a new PR for the nco mode.

2021-07-08 10:23 UTC, chan-hoo commented on scripts/exregional_run_fcst.sh
> +    echo $fhr
I'll fix this in a new PR for the nco mode.

2021-07-08 10:26 UTC, chan-hoo commented
@gsketefian, I'll add the check for SUB_HOURLY_POST, but I am not familiar with SUB_HOURLY_POST. Can you assign this 'SUB_HOURLY_POST' issue to others who know better than me?