Refactor supported input path handling.
NOAA-EMC/regional_workflow pull request #653
Opened 2021-12-15 21:30 UTC by christinaholtNOAA

## DESCRIPTION OF CHANGES: 
This PR is one of two in a series that addresses refactoring platform-dependence. The topic of this PR is to refactor the logic for supporting platforms with specific real-time data feeds. Here is a list of features and modifications that were made:

- Apply appropriate style for functions, mainly related to white space for nested code and comments.
- Make external model file offset hours configurable for analysis- and forecast-type files because sometimes we like to start a forecast from a forecast of another model.
- Refactor to reduce duplication of information.
- Set up filenames and paths to be specified with templates in a consistent way for every model instead of with bash logic that is different for every model's naming convention.
- Remove paths that do not exist on platforms I have access to: Jet and Hera.

No changes were made to the logic for input managed by USE_USER_STAGED_EXTRN_FILES or COMINGgfs for NCO mode, although it could make sense to re-assess the NCO mode handling at a later date.

I plan to go through and "review" the code to lead reviewers through this one since it bit of change. It may be helpful to view it using GitHub's ignore whitespace feature. 

## TESTS CONDUCTED: 
A single test case using the WE2E test on Hera:

    - grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GSD_SAR
   
A test case for the same forecast configuration using known paths on Hera to exercise the new code. 

I checked that arrays were consistent, that the script exits in a sane manner when files are not available on disk or HPSS, and that I haven't broken anything with the way files are handled through the "user specified" mechanism necessary for the test framework.

## ISSUE (optional): 
This work is an incremental change in support of Issue #618 

## CONTRIBUTORS (optional): 
@christopherwharrop-noaa @venitahagerty @robgonzalezpita

2021-12-15 21:59 UTC, christinaholtNOAA reviewed
I've left a bunch of (hopefully) clarifying comments for why I made the choices I made in the refactor, often citing the best-practice rule I applied. Most commonly, the changes here relate to style, reducing duplication, and reducing coupling to other system components.

Several items are meant only for staging the next phase of this work, but should still work as expected here.

2021-12-15 21:59 UTC, christinaholtNOAA commented on jobs/JREGIONAL_GET_EXTRN_MDL_FILES
> +  fi
The initial condition may not always come from an analysis file. We often want to start a forecast from a GFS forecast file, for example.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> +usage () {
Moving the usage statement to its own function to clean up readability of the main function in this file below. It also serves to help highlight necessary documentation of the function at the beginning of the file.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> -#
These variables are not used, so I pulled them out for clarity and conciseness.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> -# time of the external model forecast.
The code is clearly doing this, we do not need to explain it in a comment. This duplicates information, and is too verbose for clarity.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> +  ddd=$( $DATE_UTIL --utc --date "${yyyy}-${mm}-${dd} ${hh}:${mn} UTC" "+%j" )
It doesn't really cost anything to add these two additional variables for every case. No need to maintain the complex logic (previously on line 309) to only compute them if we're on Jet and using NAM, HRRR, FV3GFS, or RAP.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> +        fns_in_arcv=("gfs.t${hh}z.atmanl.nemsio" "gfs.t${hh}z.sfcanl.nemsio")
It's only two files. Declare them clearly.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> +        fns_in_arcv=( "${yy}${ddd}${hh}${mn}${fcst_hh}${fcst_mn}" )
This is only true for older test cases. This logic will not work for current cases where only Operational RAP/HRRR are available. I have not attempted to correct for that inconsistency in this PR, and don't plan to.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> +  fi
This logic should open us up to handle templates more effectively in config files so that we won't need to specify these sorts of things in the code itself.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
>    case "${extrn_mdl_name}" in
This case statement really should only be for those machines that have some sort of sub-structure to the base directory. In the next iteration, this logic will go away and be supported with a full templated path for each platform as I replace machine case statements with configuration files.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> -# arithmetic operations below will fail.
Remind folks that bash handles octals in a weird way. Let bash documentation handle the rest.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/set_extrn_mdl_params.sh
> -      EXTRN_MDL_SYSBASEDIR_ICS="${EXTRN_MDL_SYSBASEDIR_ICS:-}"
Here, I'm reducing coupling from configuration as much as possible. This is also a huge amount of duplication of information. If anybody ever wanted to change the name of the variable EXTRN_MDL_SYSBASEDIR_ICS in the configuration level, it would require a huge number of line changes here, too.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/set_extrn_mdl_params.sh
> -    "WCOSS_CRAY")
In this section, I have removed paths that I am able to check on Jet and Hera that no longer exist. I have also removed logic for those paths that set a default that is not a supported path for clarity.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/set_extrn_mdl_params.sh
> -case "${EXTRN_MDL_NAME_LBCS}" in
I am not sure why this logic is here and hard-coded. I have set offset hours to a configurable value with a default to 0 to replicate the result this logic captures. I also left in an if statement to set the default for RAP to 3 to duplicate this behavior (new line 128), but I have no clue why that was chosen in the first place. I think they should all be zero unless otherwise set by the user.

As far as that goes, I'm pretty sure that this logic doesn't get tested at all as part of the testing framework since all the tests use the user-defined-input mechanism, so I'm not sure it is at all relevant to hard code these values at this point.

2021-12-15 21:59 UTC, christinaholtNOAA commented on ush/set_extrn_mdl_params.sh
> -
This entire branch of paths has been removed since it was an exact duplication of the branch for ICS.

2022-01-06 21:57 UTC, christinaholtNOAA commented
Could any of the reviewers please review this PR?

@mkavulich @Jeff-Duda @gsketefian @BenjaminBlake-NOAA

2022-01-06 22:48 UTC, JeffBeck-NOAA commented
This PR conflicts with two older PRs: #580 and #650.  PR #650 is under current review, and PR #580 has been reviewed, but is waiting on comments/changes.  @gsketefian, any chance you might have time to get these two PRs squared away next week?

2022-01-06 22:56 UTC, gsketefian commented
@JeffBeck-NOAA Yes.  I just replied to @christinaholtNOAA 's comments on PR #650.  Next, I will have to compare this PR and #580 to see how they can be reconciled.

2022-01-06 23:21 UTC, christinaholtNOAA commented
PR #580 hasn't been touched for at least 3 months. That one should be closed and considered obsolete given its state of abandon.

I understand that PR #650 may conflict with this implementation, but if it gets merged first, it will be up to me to reconcile those differences.

A review of this PR could potentially negate the need for the other two. It also severely holds up the work that needs to come next to remove machine dependency from scripts -- work that is needed for us to be able to run the workflow on generic cloud platforms for automated testing.

2022-01-07 04:43 UTC, JeffBeck-NOAA commented
> PR #580 hasn't been touched for at least 3 months. That one should be closed and considered obsolete given its state of abandon.

No, it should not be closed, it's not obsolete, and it is not in a state of abandon.  @gsketefian has let other regional_workflow admins know that he has been unable to finalize the PR due to other more pressing priorities, but that he intends to review comments and complete changes soon.

> I understand that PR #650 may conflict with this implementation, but if it gets merged first, it will be up to me to reconcile those differences.

PRs are reviewed in the order they are opened.  Older PRs take precedence and code contributors must merge in updates into their forks/PRs once older PRs have been reviewed and merged.  I have been in contact with @gsketefian about PR #650, which has been reviewed and had changes made, so it is close to being merged.  Code contributors with conflicting capabilities should work together to avoid duplication and introducing parallel PRs with opposing solutions.

> A review of this PR could potentially negate the need for the other two. It also severely holds up the work that needs to come next to remove machine dependency from scripts -- work that is needed for us to be able to run the workflow on generic cloud platforms for automated testing.

My understanding was that PR #650 was opened to address this specific issue, generalizing variable templating for use across all systems, including cloud platforms.  Again, if this PR introduces an alternative but conflicting method, that needs to be resolved directly with @gsketefian first.  Then, one or two PRs can be reviewed which do not contain opposing solutions.

2022-01-07 15:59 UTC, christopherwharrop-noaa commented
@JeffBeck-NOAA - The processes you described for reviewing of PRs, and the way they are being managed is unacceptable and untenable.  #580 is absolutely abandoned and obsolete by any sane measure of software development practices.  We cannot continue development in this fashion; it isn't sustainable and it is putting very real barriers in the way of progress and causing material harm to the overall effort.  There is absolutely zero reason why PRs should always be considered only in the order in which they are received, particularly when overcome by events and new development that supersedes earlier work.  And even more so, when the PR author cannot address concerns for 3+ months.  We can't afford to continue development in this manner as it is costing us months of lost productivity.  Old work should be shelved and focus needs to shift to current efforts.  If the old work really is important and has value, it can be resubmitted in the context of current state of the repo once the author is able to commit to seeing their work all the way through the process.

2022-01-07 16:02 UTC, christinaholtNOAA commented
I've reached out to ask about the status of PR #580 and have heard no status updates, and have seen any movement on the code. I agree that we need to work together, but we cannot be held up for months on developments that are needed now. A different solution was proposed and the work that was done before has to either be merged so that I can work with that code, or it has to be abandon for the newer solution. 

I was not arguing that #650 should or should not get merged first. I need there to be a review of my code. The PR that is ready first should get merged first, and the PR that gets merged second is the one that has to deal with conflicts. It's not exactly appropriate that nobody looks at my PR until another one that could potentially be in conflict is completely merged. It is by default putting me in a position to wait for months, given the typical time it takes to merge.

PR #650 was opened without any coordination after I mentioned in PR #617 that templates are needed and that I was working on templates:

>  I am working on new development (potentially conflicting with PR #580) that works under the assumption that no variables will be expanded, and that we can store templates like in my example above in that file.

2022-01-07 16:04 UTC, christinaholtNOAA commented
I've reached out to ask about the status of PR #580 and have heard no status updates, and have seen any movement on the code. I agree that we need to work together, but we cannot be held up for months on developments that are needed now. A different solution was proposed and the work that was done before has to either be merged so that I can work with that code, or it has to be abandon for the newer solution.

I was not arguing that #650 should or should not get merged first. I need there to be a review of my code. The PR that is ready first should get merged first, and the PR that gets merged second is the one that has to deal with conflicts. It's not exactly appropriate that nobody looks at my PR until another one that could potentially be in conflict is completely merged. It is by default putting me in a position to wait for months, given the typical time it takes to merge.

PR #650 was opened without any coordination after I mentioned in PR #617 that templates are needed and that I was working on templates:

I am working on new development (potentially conflicting with PR #580) that works under the assumption that no variables will be expanded, and that we can store templates like in my example above in that file.

2022-01-07 16:33 UTC, JeffBeck-NOAA commented
@christopherwharrop-noaa, our code review standards are not unacceptable.  I should clarify my comments, though, as I wasn't completely clear.  Generally, older PRs should be cleared from the backlog first.  However, newer PRs can and should be reviewed immediately, so long as they don't conflict with older PRs, and that is the problem with this set of PRs.  I stated that the author of PR #580 has told the other code managers he will be getting back to his PR very soon, so it is not abandoned or obsolete.  He has specifically asked for it not to be closed and wishes for it to be merged.  I agree that we can't wait forever, though, and we have expressed this to the code contributor.   We also can't hold up new development with older PRs, and I agree that we shouldn't avoid reviewing newer PRs while older PRs have yet to be merged.  That is not what I was suggesting.  If a new PR from a new developer is opened that conflicts directly with an older PR, that developer should work with the other to resolve the conflict.  That is what we're dealing with here, and I'm trying to make sure that both developers are able to contribute to the code base effectively.

Something should be said for using forks of authoritative repositories for urgent, developmental needs that have immediate deadlines.  That is what we have done with the SRW App related to UFS-R2O and WPO projects, and it's worked quite well.  Once those deliverables have been met, new features and functionality can be contributed back to the authoritative repositories, which is what we've done.  But again, regardless of repo, I agree that we need to increase the speed with which we review PRs and get things merged.

@christinaholtNOAA, between PRs #580, #617, and #650, it sounds like you and @gsketefian need to meet to discuss how to proceed.  It may be best to close one or more PRs and open a new one that resolves the differences between all three.

2022-01-07 16:53 UTC, christinaholtNOAA commented
@JeffBeck-NOAA In regards to your comments on forks, this is not appropriate for the work I am proposing here. The eventual goal is to remove machine dependence for the authoritative repository so that we may be able to run automated tests of the develop branch on the cloud. In an effort to NOT open a gargantuan PR for review that would take months to review and modify, I am opening a series of PRs that take care of small chunks along the way. This is the first of several, all of which belong in develop.

We've had many discussions on the use of forks to hold code that is needed immediately by a group of developers because of our need for quick turnaround and potentially to hold prototype work that would break develop. That is not what this work is. As a code manager, suggesting that developers do not contribute code immediately to develop is inappropriate. Putting new developments on the develop branch in small, reviewable chunks is the gold standard for how all of this works, and should be upheld by repository managers. 

Holding new developments in forks for extended periods **does not** work well. Code diverges and a huge amount of technical debt must eventually be repaid as large changes are made to develop that touch hundreds of files. It is of vital importance that code that meets the needs of the develop branch should be included as quickly as possible.

2022-01-07 17:00 UTC, christopherwharrop-noaa commented
@JeffBeck-NOAA - What you are saying doesn't comport with reality.  #580 hasn't been touched in 4 months.  And three months has passed since the author last apologized for not responding to requests for changes.  In practical terms, we have already waited "forever", and yes, it is abandeone.  The author of that PR has already failed to execute their responsibilities as a code contributor and failed to commit to seeing the PR through to its conclusion in a timely manner.  At this point, it is unreasonable to trust that the work will be completed any time soon.  New work carried out in good faith should not be held hostage by ancient work that is incomplete and totally inactive, regardless of what the author of the old work wants.  The process you suggested of resolving conflicts between two outstanding PRs is also fundamentally misguided and in direct conflict with standard development processes. That is not how an efficient or effective development process works.  Professional software developers do not do that.  It is absolutely NOT the responsibility of a PR author to make sure their PR is not in conflict with other outstanding PRs.  It is the responsibility of the PR author to ensure their work doesn't conflict with the target branch to which their PR is proposed to be merged.  If someone else's PR gets their first, then THAT is when the conflicts are dealt with, by the author of the PR. The process you are suggesting is unusable and will absolutely not result in effective contributions.   A person that hasn't touched their PR in 4 months is not contributing effectively.

I also take issue with your comments about authoritative forks and I do not agree that they have worked out well after having been involved with cloud work for RRFS for the past year.  The lack of synchronization between them and the way they have been mismanaged by holding development for too long before merges has caused significant harm to projects seeking to use features that exist in multiple places.  The forks being simultaneously ahead/behind has been the band of other projects for over a year now.  The model you are describing is actually costing productivity rather than conserving it.

I don't understand the death grip on a 4 month old PR that the author is clearly not committed to.  It's time to move on.

2022-01-07 17:03 UTC, JeffBeck-NOAA commented
> @JeffBeck-NOAA In regards to your comments on forks, this is not appropriate for the work I am proposing here. The eventual goal is to remove machine dependence for the authoritative repository so that we may be able to run automated tests of the develop branch on the cloud. In an effort to NOT open a gargantuan PR for review that would take months to review and modify, I am opening a series of PRs that take care of small chunks along the way. This is the first of several, all of which belong in develop.

In that case, I agree, small PRs into the authoritative develop is the best way to approach those contributions.
 
> We've had many discussions on the use of forks to hold code that is needed immediately by a group of developers because of our need for quick turnaround and potentially to hold prototype work that would break develop. That is not what this work is. As a code manager, suggesting that developers do not contribute code immediately to develop is inappropriate. Putting new developments on the develop branch in small, reviewable chunks is the gold standard for how all of this works, and should be upheld by repository managers.

I am absolutely NOT suggesting that developers do not contribute code immediately to develop.  I am suggesting that they do this from their forks when there is not a need for an urgent merge due to an immediate deliverable.  I now understand that this PR is different, since it involves work specific to the authoritative develop branch.

> Holding new developments in forks for extended periods **does not** work well. Code diverges and a huge amount of technical debt must eventually be repaid as large changes are made to develop that touch hundreds of files. It is of vital importance that code that meets the needs of the develop branch should be included as quickly as possible.

I agree.  Code shouldn't be held in forks for a long period of time, but for urgent deliverables (that are not specifically related to the authoritative develop branch), forks work well, SO LONG AS developers merge in what they've worked on into the authoritative repos at regular intervals to avoid code divergence.  That is an absolute necessity.

2022-01-07 17:16 UTC, JeffBeck-NOAA commented
> @JeffBeck-NOAA - What you are saying doesn't comport with reality. #580 hasn't been touched in 4 months. And three months has passed since the author last apologized for not responding to requests for changes. In practical terms, we have already waited "forever", and yes, it is abandoned. The author of that PR has already failed to execute their responsibilities as a code contributor and failed to commit to seeing the PR through to its conclusion in a timely manner. At this point, it is unreasonable to trust that the work will be completed any time soon. New work carried out in good faith should not be held hostage by ancient work that is incomplete and totally inactive, regardless of what the author of the old work wants. The process you suggested of resolving conflicts between two outstanding PRs is also fundamentally misguided and in direct conflict with standard development processes. That is not how an efficient or effective development process works. Professional software developers do not do that. It is absolutely NOT the responsibility of a PR author to make sure their PR is not in conflict with other outstanding PRs. It is the responsibility of the PR author to ensure their work doesn't conflict with the target branch to which their PR is proposed to be merged. If someone else's PR gets their first, then THAT is when the conflicts are dealt with, by the author of the PR. The process you are suggesting is unusable and will absolutely not result in effective contributions. A person that hasn't touched their PR in 4 months is not contributing effectively.

@christopherwharrop-noaa, I am attempting to get two code contributors to work together to resolve conflicts between their PRs.  If I had not had recent, active discussion with the author of the older PR, I would have agreed with you to close the older PR and move forward with the newer one.

> I also take issue with your comments about authoritative forks and I do not agree that they have worked out well after having been involved with cloud work for RRFS for the past year. The lack of synchronization between them and the way they have been mismanaged by holding development for too long before merges has caused significant harm to projects seeking to use features that exist in multiple places. The forks being simultaneously ahead/behind has been the bane of other projects for over a year now. The model you are describing is actually costing productivity rather than conserving it.

I can't speak for the many other UFS repositories that may have caused your project problems.  For the UFS SRW App workflow and umbrella repos, it is a question of insufficient resources.  We do our best to push PRs through and merge them ASAP, but all our code managers have around 0.15 FTE to contribute to code management for these two repos, not nearly enough time to effectively manage these repos on a regular basis.  If there is a concern of mismanagement, that needs to be brought of with NOAA management, as we don't determine FTEs.  We try to do the best we can with the resources we're given.

2022-01-07 19:55 UTC, JeffBeck-NOAA commented
@christinaholtNOAA, thank you for scheduling a meeting for Monday to discuss the PR situation.  After talking with @gsketefian, I believe we're ready to move forward with closing #580 and combining this one, #650, and anything from #580 that is worth keeping.  @gsketefian, please feel free to clarify here.  We don't want to hold up new development, particularly when it is crucial for project deadlines, so I'm hoping we can resolve everything soon.

2022-01-07 21:10 UTC, gsketefian commented
Revealing myself as the mysterious author of PR #580, I will now make my point of view known:
1) We should not wait until PR #580 is merged for PR #653 or any other new PR to be merged, especially given that other PRs have already been merged.  That would hold up necessary development.  I apologize to @christinaholtNOAA for not getting #580 in time; I am doing my best.  If still necessary and as time allows, I will put whatever changes that are still useful in #580 into a new PR (or multiple PRs) and resubmit.
2) I am working with @christinaholtNOAA to get PR #650 to suit her needs.
3) I do not know how to solve the problem of untimely PR reviews.  My PR #580 is also a victim of this problem (although partially my fault since it is so large).  The DTC project through which the SRW App is managed is woefully under-resourced, both in terms of people and core-hours.  The resources were adequate for say the first year of the project, but as the code base and user community has grown, there hasn't been a commensurate increase in resources, maybe because EPIC is supposed to be taking over some of the responsibilities.

To avoid repeating the heated discussion above, we (obviously) need an official (i.e. written up in a document) repo management strategy -- a set of rules to point to in case disagreements arise.  I think this is a deliverable for the DTC project, but I don't believe such a document exists yet.  This would be something we can discuss in the meeting on Monday.  As part of such a strategy, we need an automated PR testing capability to run a user-specified subset of the WE2E tests (or, once in a while, all of them) on a user-specified set of platforms that creates a report that includes the hashes of the subrepos being tested, the list of tests that were run, the platforms on which they were run, and of course success/failure status of each test/platform combo.  Without this, we are finding it difficult to update the subrepo hashes (in Externals.cfg).  Maybe the DDRF work that @christinaholtNOAA et al are doing does a lot of this.

Including others in the DTC team so they are aware of this discussion.  @jwolff-ncar @JeffBeck-NOAA @mkavulich @willmayfield

2022-01-10 18:10 UTC, gsketefian commented on jobs/JREGIONAL_GET_EXTRN_MDL_FILES
> +  fi
Ok.

2022-01-10 18:21 UTC, gsketefian commented on ush/set_extrn_mdl_params.sh
> -    "WCOSS_CRAY")
Ok.  Thanks for checking those.

2022-01-10 18:25 UTC, gsketefian commented on ush/set_extrn_mdl_params.sh
> +      ;& # Fall through
That's pretty cool, haven't seen that before.  Why do you prefer this method over what I usually see:

```
"WCOSS_CRAY"|"WCOSS_DELL_P3")
  known_sys_dir=...
```

2022-01-10 18:42 UTC, gsketefian commented on ush/set_extrn_mdl_params.sh
> -      EXTRN_MDL_SYSBASEDIR_ICS="${EXTRN_MDL_SYSBASEDIR_ICS:-}"
Yes, it is a lot of duplication.  Most of it is cleared in my old PR #580, but this is fine as is.  Thanks for paring it down.

2022-01-10 18:52 UTC, gsketefian commented on ush/set_extrn_mdl_params.sh
> -case "${EXTRN_MDL_NAME_LBCS}" in
We got the "3" a long time ago from Curtis as the default to use for RAP.  But what you did is the best thing, i.e. making EXTRN_MDL_LBCS_OFFSET_HRS (and EXTRN_MDL_ICS_OFFSET_HRS) configurable.

The if-statement does get tested in any of the WE2E tests that use RAP for the LBCs.  Taking this if-statement out means EXTRN_MDL_LBCS_OFFSET_HRS needs to be set to 3 in the test configuration files of all tests that use RAP for LBCs (those files are at `regional_workflow/tests/WE2E/test_configs/...`).  Otherwise, the staged file(s) will not be found, or will be incorrectly offset.  I can do that, or we can discuss further here how to do that.  But it is definitely the better way to go.

2022-01-10 18:55 UTC, gsketefian commented on ush/set_extrn_mdl_params.sh
> -
So where does `EXTRN_MDL_SYSBASEDIR_LBCS` get set now?  I guess it should just get set to `EXTRN_MDL_SYSBASEDIR_ICS`.

2022-01-10 18:57 UTC, christinaholtNOAA commented on ush/set_extrn_mdl_params.sh
> +      ;& # Fall through
If we use the cascading syntax, we can also include additional logic there if we wanted to do something else for WCOSS_CRAY. 

```
  "FV3GFS")
    case "$MACHINE" in
    "WCOSS_CRAY")
      # set an additional variable here that only applies to WCOSS_CRAY, but EXTRN_MDL_SYSBASEDIR_ICS is the same. as next case statement 
      ;& # Fall through
      
```

2022-01-10 20:14 UTC, gsketefian commented on ush/set_extrn_mdl_params.sh
> +      ;& # Fall through
Ahhh.  Ok, thanks!

2022-01-10 20:18 UTC, gsketefian commented on ush/get_extrn_mdl_file_dir_info.sh
> -#
Yes, this needs to be done with a lot of other scripts as well (something for another PR...).

2022-01-10 20:22 UTC, gsketefian commented on ush/get_extrn_mdl_file_dir_info.sh
> -# time of the external model forecast.
Ok.

2022-01-10 20:22 UTC, gsketefian commented on ush/get_extrn_mdl_file_dir_info.sh
> +  ddd=$( $DATE_UTIL --utc --date "${yyyy}-${mm}-${dd} ${hh}:${mn} UTC" "+%j" )
Ok.

2022-01-10 20:33 UTC, gsketefian commented on ush/set_extrn_mdl_params.sh
> -case "${EXTRN_MDL_NAME_LBCS}" in
I think my last comment was wrong, let me check on that.

2022-01-10 20:37 UTC, christinaholtNOAA commented on ush/set_extrn_mdl_params.sh
> -case "${EXTRN_MDL_NAME_LBCS}" in
I totally botched this logic! What if I change the default in config_defaults.sh to an empty string, then set it to 0 or 3 here by default, depending on the external file, if it isn't already set?

2022-01-10 20:37 UTC, christinaholtNOAA commented on ush/set_extrn_mdl_params.sh
> -
Each of those get set on lines 114 and 115 of the new version of the script.
```
  else
    EXTRN_MDL_SYSBASEDIR_ICS="${EXTRN_MDL_SYSBASEDIR_ICS:-$known_sys_dir}"
    EXTRN_MDL_SYSBASEDIR_LBCS="${EXTRN_MDL_SYSBASEDIR_LBCS:-$known_sys_dir}"
  fi
```

2022-01-10 21:00 UTC, christinaholtNOAA commented on ush/set_extrn_mdl_params.sh
> -case "${EXTRN_MDL_NAME_LBCS}" in
I updated how this is handled in my last pushed commit. Do you think that will mirror the current behavior more effectively?

2022-01-10 21:27 UTC, gsketefian commented on ush/set_extrn_mdl_params.sh
> -
Ok, I see.  I just thought of something else though (unfortunately!).  `known_sys_dir` is set based on `EXTRN_MDL_NAME_ICS` only, but the big `case` statement that you're removing here checks for `EXTRN_MDL_NAME_LBCS`.  So it seems like `EXTRN_MDL_SYSBASEDIR_LBCS` will get set incorrectly since `EXTRN_MDL_NAME_ICS` and `EXTRN_MDL_NAME_LBCS` don't have to be equal. Maybe you can put the case-statement in a function and pass it a generic `extrn_mdl_name`...

2022-01-10 21:29 UTC, gsketefian commented on ush/set_extrn_mdl_params.sh
> -case "${EXTRN_MDL_NAME_LBCS}" in
I think so.

2022-01-10 22:00 UTC, gsketefian commented on ush/get_extrn_mdl_file_dir_info.sh
> -# arithmetic operations below will fail.
Ok.

2022-01-10 22:09 UTC, gsketefian commented on ush/get_extrn_mdl_file_dir_info.sh
> +        fns_in_arcv=( "nam.t${hh}z.bgrdsfi${hh}.tm00" )
I haven't tested out NAM in a long time so I don't know if the original file is even correct, but to keep the same behavior, should `tm00` be changed to `tm${hh}`?

2022-01-10 22:11 UTC, gsketefian commented on ush/get_extrn_mdl_file_dir_info.sh
> +        fns_in_arcv=("gfs.t${hh}z.atmanl.nemsio" "gfs.t${hh}z.sfcanl.nemsio")
Ok.

2022-01-10 22:40 UTC, christinaholtNOAA commented on ush/set_extrn_mdl_params.sh
> -
Good catch! This should just be one case for whatever model conditions are asked for. Let me work on that...I'll push shortly.

2022-01-10 23:09 UTC, christinaholtNOAA commented on ush/set_extrn_mdl_params.sh
> -
@gsketefian I broke this logic out into a smaller utility function in this file, and the code will call it to check for defaults separately for each of the ICS and LBCS external model.

2022-01-10 23:37 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> +        fns_in_arcv=( "nam.t${hh}z.bgrdsfi${hh}.tm00" )
My understanding of the `tm00` stamp is that it's meant to indicate "t-minus 00 hours" from the analysis time for DA purposes. I have checked a sample file from NAM on HPSS and the `bgrdsf` files available there follow a convention consistent with that understanding.

HPSS File: `/NCEPPROD/hpssprod/runhistory/rh2021/202112/20211218/com_nam_prod_nam.2021121812.bgrid.tar`
NAM files inside match this naming convention: 
```
nam.t12z.bgrdsf00.tm0[0-6]
nam.t12z.bgrdsf${fhr}.tm00
```

Note that the `i` that appears in both the original and new template is an error.

2022-01-10 23:40 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> +        fns_in_arcv=( "nam.t${hh}z.bgrdsfi${hh}.tm00" )
I also found an additional error in both the old template and new, the fcst_hr in the file was set to `${hh}`, so would have pulled the wrong file for each forecast hour not equal to the cycle time hour.

2022-01-11 00:38 UTC, JeffBeck-NOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> +        fns_in_arcv=( "nam.t${hh}z.bgrdsfi${hh}.tm00" )
I think users would generally want tm00 for initialization purposes, but I could see where it might be useful to allow for varying tm values, although that would require coding up more logic.

2022-01-11 01:59 UTC, mkavulich requested changes
A few minor comments and requested changes

2022-01-11 01:59 UTC, mkavulich commented on ush/config_defaults.sh
> +# configured here. This variale sets the number of hours earlier
variale --> variable (x2)

2022-01-11 01:59 UTC, mkavulich commented on ush/config_defaults.sh
> +EXTRN_MDL_LBCS_OFFSET_HRS="0"
Should there be a check to ensure these are compatible with each other to ensure users don't set one but not the other (resulting in BC mismatches)?

2022-01-11 01:59 UTC, mkavulich commented on ush/get_extrn_mdl_file_dir_info.sh
> +        fns_in_arcv=( "${yy}${ddd}${hh}${mn}${fcst_hh}${fcst_mn}" )
Does this mean that the App can not run with current RAP/HRRR data? If that's the case we should probably open an issue.

2022-01-11 01:59 UTC, mkavulich commented on ush/get_extrn_mdl_file_dir_info.sh
> +      The script has not set $fns_in_arcv properly"
I believe this $ should be escaped, otherwise if we ever reach this message it will just show up blank (or maybe an unset variable error?)

2022-01-11 03:12 UTC, christinaholtNOAA commented on ush/config_defaults.sh
> +EXTRN_MDL_LBCS_OFFSET_HRS="0"
Potentially? Although, there are cases where these might night both be the same...I would assume given the previous iteration of EXTRN_MDL_LBCS_OFFSET_HRS=3 only for RAP, users might enjoy setting these separately. RAP offset 3 hours, and HRRR ICS with 0 offset.

2022-01-11 03:21 UTC, christinaholtNOAA commented
@mkavulich Thanks for the review. 

I'm fairly confident that the current app can't pull data from known data streams for more recent cases using RAP/HRRR ICS/LBCS because it was using the RAP/HRRR experimental runs that were running at GSL before the last operational implementation. Once those systems were upgraded, the experimental versions were turned off. Now, the operational streams are the only ones that exist. I did not make that change in this PR, but I have updated the data streams to be consistent with the available data streams in the machine-specific configuration PR I have waiting in the wings.

2022-01-11 04:08 UTC, JeffBeck-NOAA commented
Yes, the HRRRX and RAPX data were being pulled in the App since they were, at the time, the latest versions of both, prior to the final implementations.  There's an [issue](https://github.com/NOAA-EMC/regional_workflow/issues/602) open to add paths to the operational versions, which we have wanted to include as an option to download from HPSS.  Note that the older experimental RAP and HRRR (operational and experimental) data are still available on HPSS, so the pull scripts were still working.  I think we want to go to only pulling operational versions from HPSS from now on, though.

2022-01-11 14:55 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> +        fns_in_arcv=( "nam.t${hh}z.bgrdsfi${hh}.tm00" )
The purpose of this PR is to refactor a section of code. I'd prefer not to add functionality, especially for a feature whose need is speculative in nature.

2022-01-11 16:19 UTC, JeffBeck-NOAA commented on ush/get_extrn_mdl_file_dir_info.sh
> +        fns_in_arcv=( "nam.t${hh}z.bgrdsfi${hh}.tm00" )
Yeah, not for this PR, just thinking ahead for future contributions to the App.

2022-01-11 18:35 UTC, gsketefian commented on ush/get_extrn_mdl_file_dir_info.sh
> +  fi
Ok, looks good at first glance.

2022-01-11 18:37 UTC, gsketefian commented on ush/set_extrn_mdl_params.sh
> -
Ok, looks good.

2022-01-11 18:58 UTC, gsketefian commented on ush/get_extrn_mdl_file_dir_info.sh
>    fields from which files containing initial conditions, surface fields,
I noticed that the documentation below needs an update.  Do you mind replacing the paragraph (lines ~90-92 in the new version)
```
  varname_extrn_mdl_fns:
  Name of the global variable that will contain the names of the exter-
  nal model output files.

```
with the followiing?
```
  varname_extrn_mdl_fns_on_disk:
  Name of the global variable that will contain the expected names of 
  the external model output files on disk.

  varname_extrn_mdl_fns_in_arcv:
  Name of the global variable that will contain the expected names of 
  the external model output files on NOAA HPSS.

```
Thanks.

2022-01-11 18:59 UTC, gsketefian commented on ush/get_extrn_mdl_file_dir_info.sh
> +usage () {
Ok.

2022-01-11 19:04 UTC, christinaholtNOAA commented on ush/get_extrn_mdl_file_dir_info.sh
>    fields from which files containing initial conditions, surface fields,
Sure thing.

2022-01-11 19:21 UTC, gsketefian commented on ush/config_defaults.sh
>  # FV3GFS_FILE_FMT_ICS:
Should we add to this description of EXTRN_MDL_LBCS_OFFSET_HRS how it gets set if the user doesn't explicitly specify it, i.e. 3 for RAP, 0 otherwise?

2022-01-11 19:25 UTC, gsketefian commented on ush/config_defaults.sh
> +EXTRN_MDL_LBCS_OFFSET_HRS="0"
Yes, as @christinaholtNOAA pointed out, previously they were hard-coded so that whenever one uses HRRR for ICs, there is no time offset, and if using RAP for LBCs, there is a 3 hour offset.  So they don't have to be the same.

2022-01-11 19:25 UTC, christinaholtNOAA commented on ush/config_defaults.sh
>  # FV3GFS_FILE_FMT_ICS:
I don't think so. It would be duplicate information in two different scripts, and the code that does it is clear. If we change the code in the future, the likelihood we'd remember to update that here is quite low.

2022-01-11 19:46 UTC, gsketefian commented
@christinaholtNOAA This PR looks good to me.  I suggest running a few more tests that will exercise some of the modified portions of the code.  Since we have tests for getting external files from HPSS and that code was changed quite a bit, I suggest running the following WE2E tests:
```
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019101818
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019101818
get_from_HPSS_ics_GSMGFS_lbcs_GSMGFS
get_from_HPSS_ics_HRRR_lbcs_RAP
get_from_HPSS_ics_RAP_lbcs_RAP
```
I think it is sufficient if the `get_extrn_ics` and `get_extrn_lbcs` tasks succeed.  I don't think we have any tests that get files directly from disk (e.g. using EXTRN_MDL_SYSBASEDIR_[ICS|LBCS} in the process), so we can test that capability in another PR.  Thanks.

2022-01-11 20:15 UTC, gsketefian commented on ush/config_defaults.sh
>  # FV3GFS_FILE_FMT_ICS:
Just noticed the note:
`Note: the default value is model-dependent and set in set_extrn_mdl_params.sh.
`
That's sufficient.  Thanks.

2022-01-12 15:58 UTC, christinaholtNOAA commented
@mkavulich Are you happy with the changes I made, and the responses to your questions?

I can rerun a larger test suite today, including those that include pulling from HPSS.

2022-01-12 15:58 UTC, christinaholtNOAA commented
@mkavulich Are you happy with the changes I made, and the responses to your questions?

I can rerun a larger test suite today, including those that include pulling from HPSS.

2022-01-12 16:16 UTC, gsketefian commented
@christinaholtNOAA Thanks for testing.  I will approve.  We can merge when @mkavulich gives the ok.

2022-01-12 16:16 UTC, gsketefian approved these changes

2022-01-13 00:46 UTC, christinaholtNOAA commented
I ran  a big test suite again. The following tests passed:
```
grid_CONUS_25km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_CONUS_3km_GFDLgrid_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_AK_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_AK_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_CONUS_13km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_2017_gfdlmp_regional/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_FV3GFS_suite_GSD_SAR/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_CONUS_25km_ics_FV3GFS_lbcs_RAP_suite_HRRR/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_2017_gfdlmp/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_CONUS_25km_ics_GSMGFS_lbcs_GSMGFS_suite_GFS_v15p2/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v15p2/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_CONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_NA_3km_ics_FV3GFS_lbcs_FV3GFS_suite_RRFS_v1alpha/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
grid_RRFS_SUBCONUS_3km_ics_FV3GFS_lbcs_FV3GFS_suite_GFS_v16/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
```

I also included these to test pulling from HPSS:
```
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019061200/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2019101818/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2020022518/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2020022600/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_grib2_2021010100/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019061200/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2019101818/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2020022518/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2020022600/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio_2021010100/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_nemsio/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_FV3GFS_lbcs_FV3GFS_fmt_netcdf_2021062000/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_HRRR_lbcs_RAP/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
get_from_HPSS_ics_RAP_lbcs_RAP/log.launch_FV3LAM_wflow:  Workflow status:  SUCCESS
```

I am ready for a merge when @mkavulich clears it.

2022-01-13 00:50 UTC, mkavulich commented on ush/config_defaults.sh
> +EXTRN_MDL_LBCS_OFFSET_HRS="0"
Okay then, sounds like a good thing for the future but outside the scope of this PR.

2022-01-13 00:51 UTC, mkavulich approved these changes

2022-01-13 00:56 UTC, merged